import { MasterVault } from '../types';

export const createEmptyVault = (fullName: string = '', email: string = ''): MasterVault => ({
  version: '1.0.0',
  updatedAt: new Date().toISOString(),
  profiler: {
    flags: [],
    experienceLevel: 'MID',
    location: {
      city: '',
      radiusKm: 0,
      willingnessToTravel: false,
      hybridWork: false,
      remoteOnly: false,
    },
    languages: [],
  },
  personalInfo: {
    fullName: fullName,
    email: email,
    phone: '',
    location: '',
    linkedin: '',
    github: '',
    website: '',
    photoUrl: '',
    title: '',
    summary: '',
  },
  skillsMatrix: {
    hardSkills: [],
    softSkills: [],
    toolsAndTech: [],
    certifications: [],
  },
  history: [],
  education: [],
  projects: [],
});

export const INITIAL_SAMPLE_VAULT: MasterVault = {
  version: '1.0.0',
  updatedAt: new Date().toISOString(),
  profiler: {
    flags: ['OFFICE_IT', 'REMOTE'],
    experienceLevel: 'SENIOR',
    location: {
      city: 'Warszawa',
      radiusKm: 50,
      willingnessToTravel: true,
      hybridWork: true,
      remoteOnly: false,
    },
    languages: [
      { id: '1', language: 'Polski', level: 'Native', context: 'Język ojczysty, rozmowy biznesowe i techniczne' },
      { id: '2', language: 'Angielski', level: 'C1', context: 'Dokumentacja techniczna, spotkania międzynarodowe, raporty' },
      { id: '3', language: 'Niemiecki', level: 'B1', context: 'Podstawowa komunikacja z klientami z regionu DACH' },
    ],
  },
  personalInfo: {
    fullName: 'Adrian Koziński',
    email: 'krymszuch00@outlook.com',
    phone: '+48 601 234 567',
    location: 'Warszawa, Polska',
    linkedin: 'linkedin.com/in/jankowalski-dev',
    github: 'github.com/jankowalski-dev',
    website: 'jankowalski.io',
    photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    title: 'Senior Full-Stack Engineer & Cloud Systems Architect',
    summary: 'Inżynier oprogramowania z 6+ letnim doświadczeniem w projektowaniu mikroserwisów, optymalizacji zapytań SQL oraz wdrażaniu systemów w architekturze chmurowej AWS/GCP. Doświadczony w kierowaniu zespołami developerskimi i poprawie wydajności aplikacji webowych.',
  },
  skillsMatrix: {
    hardSkills: [
      'TypeScript',
      'React.js',
      'Node.js',
      'Express',
      'Python',
      'SQL Query Optimization',
      'REST APIs',
      'GraphQL',
      'Docker',
      'Kubernetes',
      'CI/CD Pipelines',
      'PostgreSQL',
      'Redis',
      'Microservices Architecture',
      'ATS Compliance',
    ],
    softSkills: [
      'Przywództwo techniczne',
      'Komunikacja międzyzespołowa',
      'Zarządzanie czasem',
      'Rozwiązywanie złożonych problemów',
      'Mentoring juniors',
    ],
    toolsAndTech: [
      'Git',
      'AWS (EC2, S3, CloudFront, Lambda)',
      'Google Cloud Platform',
      'Jira',
      'Confluence',
      'Postman',
      'Vite',
      'Tailwind CSS',
    ],
    certifications: [
      { id: 'c1', name: 'AWS Certified Solutions Architect – Associate', issuer: 'Amazon Web Services', date: '2023-05' },
      { id: 'c2', name: 'Professional Scrum Master I (PSM I)', issuer: 'Scrum.org', date: '2022-09' },
    ],
  },
  history: [
    {
      id: 'exp1',
      company: 'TechMatrix Solutions',
      role: 'Senior Full-Stack Developer & Tech Lead',
      location: 'Warszawa (Hybrydowo)',
      startDate: '01/2022',
      endDate: 'Obecnie',
      isCurrent: true,
      highlights: [
        {
          id: 'h1',
          text: 'Zoptymalizowałem zapytania SQL i strukturę bazy PostgreSQL, co skróciło czas odpowiedzi API o 42% dla ponad 150 000 użytkowników dziennie.',
          action: 'Zoptymalizowałem',
          target: 'zapytania SQL i strukturę bazy PostgreSQL',
          tool: 'PostgreSQL, Redis, PGStat',
          metric: 'skrócenie czasu odpowiedzi API o 42% dla 150k+ użytkowników dziennie',
          keywords: ['SQL', 'PostgreSQL', 'API', 'Optimization', 'Database', 'Redis'],
        },
        {
          id: 'h2',
          text: 'Zaprojektowałem i wdrożyłem architekturę mikroserwisów w Node.js i Dockerze, redukując opóźnienia transakcyjne o 35%.',
          action: 'Zaprojektowałem i wdrożyłem',
          target: 'architekturę mikroserwisów backendowych',
          tool: 'Node.js, Express, Docker, Kubernetes',
          metric: 'redukcja opóźnień transakcyjnych o 35%',
          keywords: ['Microservices', 'Node.js', 'Docker', 'Kubernetes', 'Backend', 'Architecture'],
        },
        {
          id: 'h3',
          text: 'Kierowałem 5-osobowym zespołem programistów Frontend/Backend, wdrażając praktyki Code Review i automatyczne testy CI/CD z pokryciem 85%.',
          action: 'Kierowałem',
          target: 'zespołem programistów i procesem CI/CD',
          tool: 'GitHub Actions, Jest, TypeScript, Jira',
          metric: 'pokrycie testami 85% oraz skrócony czas wdrażania zmian o 50%',
          keywords: ['Tech Lead', 'Code Review', 'CI/CD', 'TypeScript', 'Jest', 'Agile'],
        },
      ],
    },
    {
      id: 'exp2',
      company: 'CloudSphere Software',
      role: 'Full-Stack Developer',
      location: 'Kraków (Zdalnie)',
      startDate: '06/2019',
      endDate: '12/2021',
      isCurrent: false,
      highlights: [
        {
          id: 'h4',
          text: 'Stworzyłem dynamiczny interfejs użytkownika w React.js i TypeScript dla systemu analitycznego, obsługujący ponad 2 miliony rekordów danych rocznie.',
          action: 'Stworzyłem',
          target: 'interfejs użytkownika systemu analitycznego',
          tool: 'React.js, TypeScript, Redux Toolkit, Tailwind CSS',
          metric: 'obsługa 2M+ rekordów danych rocznie z płynnością 60 FPS',
          keywords: ['React.js', 'TypeScript', 'Frontend', 'Redux', 'UI/UX', 'Performance'],
        },
        {
          id: 'h5',
          text: 'Zintegrowałem zewnętrzne interfejsy API REST i WebSocket dla powiadomień w czasie rzeczywistym, co podniosło zaangażowanie użytkowników o 28%.',
          action: 'Zintegrowałem',
          target: 'interfejsy API REST i system powiadomień WebSocket',
          tool: 'REST API, WebSockets, Express.js',
          metric: 'wzrost zaangażowania użytkowników o 28%',
          keywords: ['REST API', 'WebSockets', 'Integration', 'Real-time', 'Express'],
        },
      ],
    },
  ],
  education: [
    {
      id: 'edu1',
      institution: 'Politechnika Warszawska',
      degree: 'Magister Inżynier',
      fieldOfStudy: 'Informatyka i Systemy Wbudowane',
      startDate: '10/2014',
      endDate: '06/2019',
      description: 'Specjalność: Architektura Oprogramowania i Inżynieria Baz Danych. Praca dyplomowa z optymalizacji rozproszonych systemów bazodanowych.',
    },
  ],
  projects: [
    {
      id: 'p1',
      name: 'E-Commerce Microservices Engine',
      role: 'Creator & Maintainer',
      description: 'System skracający czas przetwarzania zamówień internetowych w architekturze kontenerowej.',
      techStack: ['Node.js', 'TypeScript', 'Docker', 'PostgreSQL', 'Redis'],
      metrics: 'Przepustowość 500 req/s przy użyciu pamięci < 250MB',
      link: 'github.com/jankowalski-dev/ecommerce-engine',
    },
  ],
};
