import { PrerecordedInterviewQuestion } from './types';

/**
 * 35 najtrafniejszych, wzorcowych pytań rekrutacyjnych (Prerecorded / Scenariusze STAR).
 * Obejmuje pytania behawioralne, techniczne, branżowe (fizyczne/techniczne) oraz managerskie.
 */
export const PRERECORDED_INTERVIEW_QUESTIONS: PrerecordedInterviewQuestion[] = [
  // =========================================================================
  // I. BEHAVIORAL & PROBLEM SOLVING (10 pytań)
  // =========================================================================
  {
    id: 'prerecorded_b01',
    question: 'Opowiedz o najpoważniejszym błędzie lub awarii, za którą odpowiadałeś, i jak krok po kroku opanowałeś sytuację.',
    category: 'BEHAVIORAL',
    intent: 'Bada dojrzałość, brak przerzucania winy na innych, umiejętność analizy przyczyn (RCA) i wdrożenie działań zapobiegawczych.',
    starHint: {
      situation: 'Zdefiniuj incydent, jego skalę i bezpośrednie skutki operacyjne.',
      task: 'Twoja odpowiedzialność za natychmiastowe zatrzymanie eskalacji.',
      action: 'Działania naprawcze, komunikacja z zespołem/klientem, wdrożenie procedury prewencyjnej.',
      result: 'Czas usunięcia awarii, brak powtórzenia błędu, wnioski wyciągnięte dla procedur firmy.',
    },
    recommendedDurationSec: 60,
    tags: ['awaria', 'błąd', 'odpowiedzialność', 'rca'],
  },
  {
    id: 'prerecorded_b02',
    question: 'Opowiedz o sytuacji, gdy musiałeś podjąć kluczową decyzję techniczną lub operacyjną przy niepełnych danych i pod presją czasu.',
    category: 'BEHAVIORAL',
    intent: 'Bada zarządzanie ryzykiem, logiczne myślenie pod presją i zdolność priorytetyzacji faktów nad emocjami.',
    starHint: {
      situation: 'Nagła sytuacja bez możliwości przeprowadzenia pełnych konsultacji.',
      task: 'Wybór między 2-3 wariantami o różnym profilu ryzyka.',
      action: 'Kryteria oceny, selekcja wariantu i przejęcie odpowiedzialności za egzekucję.',
      result: 'Wymierny skutek decyzji i uzyskany rezultat biznesowy/techniczny.',
    },
    recommendedDurationSec: 60,
    tags: ['decyzje', 'presja czasu', 'zarządzanie ryzykiem'],
  },
  {
    id: 'prerecorded_b03',
    question: 'Opowiedz o projekcie lub zadaniu, z którego wymiernych rezultatów liczbowych jesteś najbardziej dumny.',
    category: 'BEHAVIORAL',
    intent: 'Bada orientację na mierzalne rezultaty biznesowe (ROI, KPI, czas, koszt) zamiast samego „bycia zajętym”.',
    starHint: {
      situation: 'Punkt wyjścia i problem biznesowy (np. wysoki koszt, niska przepustowość).',
      task: 'Cel liczbowy postawiony przed Twoją rolą.',
      action: 'Konkretne innowacje, narzędzia i etapy wdrożenia zrealizowane przez Ciebie.',
      result: 'Twarde dane: % wzrostu wydajności, zaoszczędzone godziny lub kwoty.',
    },
    recommendedDurationSec: 60,
    tags: ['sukces', 'metryki', 'kpi', 'osiągnięcia'],
  },
  {
    id: 'prerecorded_b04',
    question: 'Jak poradziłeś sobie z sytuacją, gdy w trakcie realizacji zadania diametralnie zmieniły się wymagania lub priorytety?',
    category: 'BEHAVIORAL',
    intent: 'Bada elastyczność adaptacyjną, odporność na frustrację i sprawne przeorganizowanie zasobów.',
    starHint: {
      situation: 'Projekt w zaawansowanej fazie i nagły zwrot decyzji biznesowej/klienta.',
      task: 'Konieczność minimalizacji strat wykonanej pracy i szybkie przeformatowanie planu.',
      action: 'Audyt wykonanych prac, ustalenie nowego harmonogramu, transparentna komunikacja.',
      result: 'Dowiezienie zmienionego zakresu bez przekroczenia krytycznego terminu.',
    },
    recommendedDurationSec: 60,
    tags: ['adaptacja', 'zmiana priorytetów', 'elastyczność'],
  },
  {
    id: 'prerecorded_b05',
    question: 'Opowiedz o sytuacji, gdy musiałeś odmówić przełożonemu lub klientowi (asertywność techniczna/biznesowa).',
    category: 'BEHAVIORAL',
    intent: 'Bada asertywność opartą na dowodach, troskę o jakość i bezpieczeństwo projektu wbrew nierealnym żądaniom.',
    starHint: {
      situation: 'Żądanie wykonania zadania w nierealnym terminie lub z pominięciem procedur bezpieczeństwa.',
      task: 'Obrona standardów jakościowych i transparentne pokazanie konsekwencji.',
      action: 'Przedstawienie faktów, alternatywnego planu i kompromisu opartego na danych.',
      result: 'Akceptacja alternatywy przez drugą stronę, uniknięcie długu technicznego lub wypadku.',
    },
    recommendedDurationSec: 60,
    tags: ['asertywność', 'komunikacja', 'negocjacje'],
  },
  {
    id: 'prerecorded_b06',
    question: 'Opowiedz o sytuacji, w której Twoja inicjatywa usprawniła powtarzalny proces w zespole lub firmie.',
    category: 'BEHAVIORAL',
    intent: 'Bada proaktywność, myślenie optymalizacyjne i eliminację marnotrawstwa (Lean/Kaizen).',
    starHint: {
      situation: 'Powtarzalny, czasochłonny proces generujący opóźnienia lub błędy.',
      task: 'Decyzja o wdrożeniu standaryzacji, szablonu lub automatyzacji.',
      action: 'Zaprojektowanie nowego schematu, przetestowanie i wdrożenie w zespole.',
      result: 'Zredukowanie czasu obsługi o X% i zadowolenie współpracowników.',
    },
    recommendedDurationSec: 60,
    tags: ['innowacja', 'usprawnienie', 'automatyzacja'],
  },
  {
    id: 'prerecorded_b07',
    question: 'Jak radzisz sobie z monotonnymi lub wysoce powtarzalnymi zadaniami wymagającymi stuprocentowej dokładności?',
    category: 'BEHAVIORAL',
    intent: 'Bada samodyscyplinę, dbałość o detale i mechanizmy samokontroli (self-check).',
    starHint: {
      situation: 'Zadanie o wysokiej powtarzalności (np. audyt, dokumentacja, kontrola jakości).',
      task: 'Utrzymanie zera błędów przy dużej skali operacji.',
      action: 'Własne checklisty, podział pracy na interwały, weryfikacja krzyżowa.',
      result: 'Bezszkodowa realizacja i wysoka ocena odbiorcza.',
    },
    recommendedDurationSec: 60,
    tags: ['dokładność', 'checklisty', 'jakość'],
  },
  {
    id: 'prerecorded_b08',
    question: 'Opowiedz o sytuacji, gdy projekt lub zadanie zakończyło się niepowodzeniem i czego Cię to nauczyło.',
    category: 'BEHAVIORAL',
    intent: 'Bada samoświadomość, zdolność wyciągania lekcji z porażek i brak postawy obronnej.',
    starHint: {
      situation: 'Nieudane wdrożenie, niezrealizowany cel lub utracony kontrakt.',
      task: 'Analiza co poszło nie tak na poziomie planowania i egzekucji.',
      action: 'Podsumowanie z zespołem, zdefiniowanie luk w procesie.',
      result: 'Wdrożona nowa reguła, która w kolejnym projekcie przyniosła sukces.',
    },
    recommendedDurationSec: 60,
    tags: ['porażka', 'nauka', 'post-mortem'],
  },
  {
    id: 'prerecorded_b09',
    question: 'W jaki sposób organizujesz swój dzień pracy, gdy masz do wykonania 5 pilnych zadań z różnych obszarów?',
    category: 'BEHAVIORAL',
    intent: 'Bada metodykę zarządzania czasem (Eisenhower, Kanban, Timeboxing) i umiejętność komunikowania statusu.',
    starHint: {
      situation: 'Nagromadzenie zadań z różnych źródeł w jednym czasie.',
      task: 'Ustalenie kryteriów ważności i pilności.',
      action: 'Matryca priorytetów, poinformowanie interesariuszy o realnych terminach, wykonanie.',
      result: 'Dowiezienie zadań krytycznych na czas, bez chaosu organizacyjnego.',
    },
    recommendedDurationSec: 60,
    tags: ['organizacja pracy', 'priorytetyzacja', 'czas'],
  },
  {
    id: 'prerecorded_b10',
    question: 'Co robisz, gdy napotykasz problem techniczny lub biznesowy, którego nigdy wcześniej nie rozwiązywałeś?',
    category: 'BEHAVIORAL',
    intent: 'Bada zdolności badawcze, umiejętność czytania dokumentacji, szukania wiedzy i szybkiej syntezy.',
    starHint: {
      situation: 'Nietypowa usterka, nowa technologia lub nieznany przypadek brzegowy.',
      task: 'Zdobycie niezbędnej wiedzy w krótkim czasie.',
      action: 'Studiowanie dokumentacji DTR / RFC, konsultacja ze specjalistami, testy w środowisku bezpiecznym.',
      result: 'Rozwiązanie problemu i udokumentowanie wiedzy (baza wiedzy) dla innych.',
    },
    recommendedDurationSec: 60,
    tags: ['learning', 'samodzielność', 'badania'],
  },

  // =========================================================================
  // II. TECHNICAL & OPERATIONAL STANDARDS (10 pytań)
  // =========================================================================
  {
    id: 'prerecorded_t01',
    question: 'Jak przeprowadzasz proces diagnozy i lokalizacji usterki (Root Cause Analysis), gdy system lub maszyna nie działa prawidłowo?',
    category: 'TECHNICAL',
    intent: 'Bada systematyczność inżynierską, eliminację hipotez krok po kroku i użycie narzędzi diagnostycznych.',
    starHint: {
      situation: 'Zgłoszenie objawowe o awarii (np. brak parametrów, błąd 500, zatrzymanie linii).',
      task: 'Identyfikacja faktycznej przyczyny źródłowej, a nie tylko gaszenie symptomów.',
      action: 'Pomiary aparatury, logi, analiza od gałęzi najprostszych do złożonych.',
      result: 'Wskazanie i wymiana wadliwego elementu/kodu, przywrócenie pracy w 100%.',
    },
    recommendedDurationSec: 60,
    tags: ['diagnostyka', 'rca', 'analiza techniczna'],
  },
  {
    id: 'prerecorded_t02',
    question: 'W jaki sposób dbasz o jakość dokumentacji technicznej i procedur w swoich projektach?',
    category: 'TECHNICAL',
    intent: 'Bada czy kandydat tworzy czytelny ślad rewizyjny (as-built, schematy, procedury) umożliwiający przejęcie prac przez innych.',
    starHint: {
      situation: 'Wdrażanie nowego rozwiązania lub modyfikacja istniejącej instalacji.',
      task: 'Zapewnienie pełnej odtwarzalności i zgodności z normami.',
      action: 'Opracowanie dokumentacji powykonawczej, schematów blokowych, instrukcji stanowiskowych.',
      result: 'Skrócenie czasu wdrożenia nowych pracowników i bezproblemowy odbiór UDT/audytowy.',
    },
    recommendedDurationSec: 60,
    tags: ['dokumentacja', 'standardy', 'procedury'],
  },
  {
    id: 'prerecorded_t03',
    question: 'Opowiedz o kompromisie architektonicznym lub technologicznym, na który musiałeś pójść ze względu na budżet lub czas.',
    category: 'TECHNICAL',
    intent: 'Bada pragmatyzm techniczny – świadomość ograniczeń biznesowych i plan zarządzania długiem technicznym.',
    starHint: {
      situation: 'Brak budżetu lub czasu na rozwiązanie idealne.',
      task: 'Dobór wariantu optymalnego ekonomicznie i bezpiecznego eksploatacyjnie.',
      action: 'Świadomy wybór komponentów, zabezpieczenie punktów krytycznych.',
      result: 'Uruchomienie w budżecie z jasnym planem rozbudowy w kolejnym etapie.',
    },
    recommendedDurationSec: 60,
    tags: ['architektura', 'kompromisy', 'trade-offs'],
  },
  {
    id: 'prerecorded_t04',
    question: 'Jakie mechanizmy kontroli jakości (Quality Assurance / Kontrola Odbiorcza) stosujesz przed przekazaniem pracy do odbioru?',
    category: 'TECHNICAL',
    intent: 'Bada rygor weryfikacji przedoddaniowej (testy jednostkowe, próby ciśnieniowe, pomiary odbiorcze, inspekcja VT).',
    starHint: {
      situation: 'Finał prac montażowych, wdrożeniowych lub programistycznych.',
      task: 'Upewnienie się o 100% zgodności ze specyfikacją przed wizytą inwestora/klienta.',
      action: 'Przeprowadzenie procedury testowej (próby szczelności, testy integracyjne, pomiary).',
      result: 'Protokół odbioru bez uwag w pierwszym podejściu.',
    },
    recommendedDurationSec: 60,
    tags: ['qa', 'kontrola jakości', 'odbiory'],
  },
  {
    id: 'prerecorded_t05',
    question: 'Jakie zasady cyberbezpieczeństwa lub ochrony danych poufnych (RODO / tajemnica przedsiębiorstwa) stosujesz na co dzień?',
    category: 'TECHNICAL',
    intent: 'Bada higienę bezpieczeństwa: zarządzanie dostępami, szyfrowanie, procedury haseł, brak wycieków.',
    starHint: {
      situation: 'Praca z danymi wrażliwymi, kluczami API, danymi klientów lub projektami strategicznymi.',
      task: 'Ochrona przed wyciekiem i nieautoryzowanym dostępem.',
      action: '2FA, polityka least privilege, anonimizacja danych testowych, bezpieczne kanały transferu.',
      result: 'Zero incydentów bezpieczeństwa, pozytywny wynik audytu zgodności.',
    },
    recommendedDurationSec: 60,
    tags: ['bezpieczeństwo', 'rodo', 'cybersecurity'],
  },
  {
    id: 'prerecorded_t06',
    question: 'W jaki sposób optymalizujesz wydajność i zużycie zasobów (czas cyklu, zapytania, zużycie energii/materiałów)?',
    category: 'TECHNICAL',
    intent: 'Bada umiejętność profilowania, pomiaru przed/po (Reguła 6) i eliminowania wąskich gardeł (bottlenecks).',
    starHint: {
      situation: 'Wykrycie wąskiego gardła spowalniającego proces lub generującego wysokie koszty.',
      task: 'Przeprowadzenie precyzyjnego pomiaru wyjściowego i zaplanowanie optymalizacji.',
      action: 'Identyfikacja problemu, rekonfiguracja parametrów, indeksowanie lub zmiana technologii.',
      result: 'Konkretna liczba przed i po (np. redukcja czasu z 4.2s do 320ms / spadek strat materiału o 18%).',
    },
    recommendedDurationSec: 60,
    tags: ['optymalizacja', 'wydajność', 'pomiary'],
  },
  {
    id: 'prerecorded_t07',
    question: 'Jak podchodzisz do automatyzacji powtarzalnych zadań w swoim środowisku pracy?',
    category: 'TECHNICAL',
    intent: 'Bada umiejętność budowy skryptów, pipeline’ów, automatycznych szablonów i eliminację pracy ręcznej.',
    starHint: {
      situation: 'Czynność wykonywana ręcznie przez kilkadziesiąt minut dziennie.',
      task: 'Zastąpienie jej powtarzalnym, bezobsługowym procesem.',
      action: 'Stworzenie skryptu / automatyzacji / szablonu z obsługą błędów.',
      result: 'Zaoszczędzenie X godzin tygodniowo i wyeliminowanie błędów ludzkich.',
    },
    recommendedDurationSec: 60,
    tags: ['automatyzacja', 'skrypty', 'ci/cd'],
  },
  {
    id: 'prerecorded_t08',
    question: 'Opowiedz o sytuacji, gdy musiałeś zintegrować dwa zupełnie różne systemy lub urządzenia, które domyślnie ze sobą nie współpracowały.',
    category: 'TECHNICAL',
    intent: 'Bada umiejętność mostkowania protokołów, interfejsów, API i rozwiązywania konfliktów formatów danych.',
    starHint: {
      situation: 'Konieczność spięcia starszego sprzętu/systemu legacy z nowoczesnym rozwiązaniem.',
      task: 'Zapewnienie stabilnej, dwukierunkowej wymiany danych.',
      action: 'Stworzenie warstwy translacji, konwertera sygnałów lub middleware API.',
      result: 'Płynna transmisja danych bez utraty pakietów.',
    },
    recommendedDurationSec: 60,
    tags: ['integracja', 'protokoły', 'api'],
  },
  {
    id: 'prerecorded_t09',
    question: 'W jaki sposób monitorujesz stan środowiska produkcyjnego/operacyjnego, aby zapobiegać awariom zanim zauważy je użytkownik?',
    category: 'TECHNICAL',
    intent: 'Bada proaktywny monitoring, alertowanie i prewencję zamiast reaktywnego gaszenia pożarów.',
    starHint: {
      situation: 'Infrastruktura o wysokich wymaganiach dostępności (SLA 99.9%).',
      task: 'Wdrożenie metryk ostrzegawczych przed osiągnięciem stanów krytycznych.',
      action: 'Konfiguracja progów alertowania, monitoring parametrów życiowych systemu/maszyny.',
      result: 'Wychwycenie degradacji i naprawa w oknie serwisowym bez przerw w działaniu.',
    },
    recommendedDurationSec: 60,
    tags: ['monitoring', 'alertowanie', 'sla'],
  },
  {
    id: 'prerecorded_t10',
    question: 'Jak postępujesz w przypadku konieczności wykonania prac serwisowych w środowisku pracującym pod ciągłym obciążeniem (Zero Downtime)?',
    category: 'TECHNICAL',
    intent: 'Bada przygotowanie planów rollbacku, środowisk równoległych (blue-green) i bezpieczeństwa ciągłości działania.',
    starHint: {
      situation: 'Konieczność wdrożenia zmian bez przerywania pracy systemu/linii.',
      task: 'Zminimalizowanie ryzyka i przygotowanie procedury awaryjnego powrotu.',
      action: 'Prace etapowe, testy na kanarku, przygotowanie scenariusza natychmiastowego rollbacku.',
      result: '100% ciągłość pracy dla użytkowników i klientów końcowych.',
    },
    recommendedDurationSec: 60,
    tags: ['zero-downtime', 'rollback', 'utrzymanie ruchu'],
  },

  // =========================================================================
  // III. TRADE, CRAFT & PRACE FIZYCZNE/SPECJALISTYCZNE (8 pytań - Reguła 8)
  // =========================================================================
  {
    id: 'prerecorded_tr01',
    tradeSpecialization: 'BHP & Uprawnienia',
    question: 'Opowiedz o sytuacji, w której warunki na stanowisku pracy stwarzały bezpośrednie zagrożenie wypadkiem i jak zareagowałeś (BHP / SEP / UDT).',
    category: 'TRADE',
    intent: 'Bada bezwzględny priorytet życia i zdrowia ludzkiego, zatrzymanie prac w razie zagrożenia i egzekwowanie procedur BHP.',
    starHint: {
      situation: 'Wykrycie niebezpieczeństwa (np. brak uziemienia, praca na wysokości bez asekuracji, wyciek gazu).',
      task: 'Natychmiastowe zabezpieczenie strefy i powstrzymanie niebezpiecznych czynności.',
      action: 'Wstrzymanie prac, zgłoszenie do kierownika budowy/zakładu, wdrożenie właściwych zabezpieczeń.',
      result: '0 wypadków, bezpieczne dokończenie robót po usunięciu zagrożenia.',
    },
    recommendedDurationSec: 60,
    tags: ['bhp', 'bezpieczeństwo', 'sep', 'udt'],
  },
  {
    id: 'prerecorded_tr02',
    tradeSpecialization: 'Instalacje & HVAC',
    question: 'W jaki sposób przeprowadzasz protokół prób szczelności i analizy spalin przy pierwszym uruchomieniu kotła gazowego lub pompy ciepła?',
    category: 'TRADE',
    intent: 'Bada znajomość procedur montażowych, norm technicznych, użycie analizatora spalin i uprawnień F-Gaz / SEP G3.',
    starHint: {
      situation: 'Montaż nowej instalacji grzewczej u klienta indywidualnego lub przemysłowego.',
      task: 'Przeprowadzenie prób ciśnieniowych i kalibracji parametrów pracy zgodnie z DTR producenta.',
      action: 'Próba azotowa, odpowietrzenie, pomiar analizatorem Testo, sprawdzenie ciągu i zabezpieczeń.',
      result: 'Sporządzenie protokołu uruchomieniowego, bezpieczna i ekonomiczna praca urządzenia.',
    },
    recommendedDurationSec: 60,
    tags: ['hvac', 'kotły', 'pompy ciepła', 'analiza spalin'],
  },
  {
    id: 'prerecorded_tr03',
    tradeSpecialization: 'Spawalnictwo & Ślusarstwo',
    question: 'Jak dobierasz parametry spawania (metoda TIG 141 / MAG 135) i przygotowujesz złącze, aby bez problemu przejść badania wizualne VT2 i radiograficzne RTG?',
    category: 'TRADE',
    intent: 'Bada znajomość metalurgii spoin, ukosowania krawędzi, doboru gazów osłonowych i normy PN-EN ISO 9606.',
    starHint: {
      situation: 'Zadanie wykonania spoin doczołowych rurociągu ciśnieniowego lub konstrukcji nośnej.',
      task: 'Zapewnienie pełnego przetopu bez porów, podtopień i niezgodności spawalniczych.',
      action: 'Dokładne oczyszczenie i ukosowanie krawędzi, dobór natężenia prądu, gazu osłonowego i techniki prowadzenia.',
      result: 'Wynik badań nieniszczących (NDT) VT2/RTG: 100% pozytywny bez konieczności poprawek.',
    },
    recommendedDurationSec: 60,
    tags: ['spawanie', 'tig', 'mag', 'ndt', 'vt2'],
  },
  {
    id: 'prerecorded_tr04',
    tradeSpecialization: 'Elektryka & Automatyka',
    question: 'Opowiedz o procesie prefabrykacji lub modernizacji szafy rozdzielczej nn i jak wykonujesz pomiary odbiorcze miernikiem wielofunkcyjnym (np. Sonel)?',
    category: 'TRADE',
    intent: 'Bada czytanie schematów elektrycznych EPLAN, estetykę sznurowania kabli, pomiary RCD, impedancji pętli zwarcia i izolacji.',
    starHint: {
      situation: 'Nowy układ zasilania lub automatyki w obiekcie komercyjnym/produkcyjnym.',
      task: 'Montaż aparatury, oznaczenie przewodów i przeprowadzenie pomiarów zgodnie z normą PN-HD 60364.',
      action: 'Sznurowanie koryt grzebieniowych, wykonanie pomiarów Riso, Zs i czasu zadziałania RCD.',
      result: 'Kompletny protokół pomiarowy SEP, bezpieczne podanie napięcia pod odbiór inspektora.',
    },
    recommendedDurationSec: 60,
    tags: ['elektryka', 'sep', 'pomiary', 'rozdzielnice'],
  },
  {
    id: 'prerecorded_tr05',
    tradeSpecialization: 'Logistyka & Magazyn',
    question: 'Jak organizujesz bezpieczną i wydajną kompletację zamówień w magazynie wysokiego składowania przy jednoczesnym rozładunku dostaw i pracy wózków UDT?',
    category: 'TRADE',
    intent: 'Bada znajomość systemów WMS, obsługi wózków Reach Truck, zasad FIFO/FEFO oraz procedur antykolizyjnych w alejkach.',
    starHint: {
      situation: 'Szczyt operacyjny w centrum dystrybucyjnym z napiętym oknem wysyłkowym.',
      task: 'Koordynacja przyjęcia towaru, zasilenia regałów i bezbłędnej kompletacji.',
      action: 'Optymalizacja ścieżki zbiórki ze skanerem Zebra, kontrola etykiet GS1, bezpieczna strefa dla wózków.',
      result: '100% terminowość wydań bez uszkodzeń palet i pomyłek w asortymencie.',
    },
    recommendedDurationSec: 60,
    tags: ['magazyn', 'wms', 'udt', 'logistyka'],
  },
  {
    id: 'prerecorded_tr06',
    tradeSpecialization: 'Transport & Spedycja',
    question: 'W jaki sposób zarządzasz czasem jazdy i odpoczynku (AETR / tachograf) oraz zabezpieczeniem ładunku pasami, gdy na trasie pojawiają się nieprzewidziane zatory drogowe?',
    category: 'TRADE',
    intent: 'Bada bezwzględną znajomość przepisów czasu pracy kierowców, atestów pasów ERGO, mat antypoślizgowych i procedur CMR.',
    starHint: {
      situation: 'Trasa międzynarodowa z wąskim oknem awizacji w magazynie docelowym i utrudnienia drogowe.',
      task: 'Dowiezienie ładunku bez naruszenia czasu pracy i bez uszkodzenia towaru.',
      action: 'Prawidłowe rozmieszczenie nacisków na osie, spięcie ładunku, bieżąca rewizja trasy na nawigacji ciężarowej.',
      result: 'Dostawa na czas, 0 mandatów ITD, czysty protokół CMR.',
    },
    recommendedDurationSec: 60,
    tags: ['transport', 'c+e', 'aetr', 'tachograf'],
  },
  {
    id: 'prerecorded_tr07',
    tradeSpecialization: 'Obróbka CNC & Produkcja',
    question: 'Jak przygotowujesz i ustawiasz detal na obrabiarce CNC (frezarka/tokarka) oraz weryfikujesz kod G-code i korekcje narzędzi, aby uniknąć kolizji i braków?',
    category: 'TRADE',
    intent: 'Bada znajomość sterowań Sinumerik/Fanuc, bazowania sondą Renishaw, kontroli wymiarowej mikrometrem/średnicówką i norm tolerancji ISO.',
    starHint: {
      situation: 'Uruchomienie nowej partii produkcyjnej skomplikowanego detalu ze stali stopowej.',
      task: 'Wykonanie pierwszej sztuki wzorcowej w tolerancji +/- 0.01 mm.',
      action: 'Bindowanie narzędzi, bazowanie punktu zerowego, symulacja na sucho (Dry Run), korekta promieniowa.',
      result: 'Pierwsza sztuka zaakceptowana przez dział kontroli jakości (KJ), bezkolizyjna praca seryjna.',
    },
    recommendedDurationSec: 60,
    tags: ['cnc', 'g-code', 'obróbka', 'jakość'],
  },
  {
    id: 'prerecorded_tr08',
    tradeSpecialization: 'Medycyna & Ochrona Zdrowia',
    question: 'Opowiedz o postępowaniu w nagłym pogorszeniu stanu pacjenta lub procedurze triage i jak zapewniasz rygorystyczne przestrzeganie procedur sanitarno-epidemiologicznych.',
    category: 'TRADE',
    intent: 'Bada opanowanie w sytuacjach zagrożenia życia, znajomość procedur RKO/ALS, precyzję podawania leków i prowadzenie dokumentacji EDM.',
    starHint: {
      situation: 'Nagła zapaść krążeniowo-oddechowa lub konieczność pilnej interwencji.',
      task: 'Natychmiastowe wdrożenie algorytmu ratunkowego i wezwanie zespołu reanimacyjnego.',
      action: 'Udrożnienie dróg oddechowych, dostęp naczyniowy, monitorowanie parametrów życiowych, podanie leków wg zlecenia.',
      result: 'Stabilizacja pacjenta, bezpieczne przekazanie na OIT i rzetelny wpis w EDM.',
    },
    recommendedDurationSec: 60,
    tags: ['medycyna', 'pwz', 'rko', 'triage'],
  },

  // =========================================================================
  // IV. LEADERSHIP, COLLABORATION & CLIENT RELATIONS (7 pytań)
  // =========================================================================
  {
    id: 'prerecorded_l01',
    question: 'Jak poradziłeś sobie z konfliktem personalnym lub merytorycznym w zespole, który zagrażał terminowi realizacji projektu?',
    category: 'LEADERSHIP',
    intent: 'Bada dojrzałość interpersonalną, deeskalację emocji, sprowadzenie dyskusji do faktów i dbałość o morale.',
    starHint: {
      situation: 'Spór między kluczowymi specjalistami dotyczący sposobu realizacji zadania.',
      task: 'Zatrzymanie polaryzacji i wypracowanie wspólnego porozumienia.',
      action: 'Rozmowy indywidualne, moderowane spotkanie robocze, zdefiniowanie kryteriów wyboru.',
      result: 'Powrót do efektywnej pracy zespołowej i dowiezienie projektu w terminie.',
    },
    recommendedDurationSec: 60,
    tags: ['konflikt', 'zespół', 'komunikacja'],
  },
  {
    id: 'prerecorded_l02',
    question: 'Opowiedz o trudnych negocjacjach lub rozmowie z niezadowolonym klientem, który chciał zerwać umowę lub zgłosił poważną reklamację.',
    category: 'CLIENT',
    intent: 'Bada opanowanie, empatię połączoną z ochroną interesu firmy, konstruowanie propozycji win-win i odbudowę zaufania.',
    starHint: {
      situation: 'Wściekły klient z powodu opóźnienia lub wady produktu/usługi.',
      task: 'Deeskalacja emocji, rzetelne zbadanie sprawy i przedstawienie planu naprawczego.',
      action: 'Wysłuchanie bez przerywania, natychmiastowe zaoferowanie kompensaty/naprawy, codzienne raportowanie statusu.',
      result: 'Klient utrzymał współpracę i przedłużył kontrakt na kolejny rok.',
    },
    recommendedDurationSec: 60,
    tags: ['klient', 'reklamacja', 'negocjacje'],
  },
  {
    id: 'prerecorded_l03',
    question: 'W jaki sposób wprowadzasz (onboarding) i szkolisz nowego pracownika, aby szybko stał się w pełni samodzielny?',
    category: 'LEADERSHIP',
    intent: 'Bada umiejętność dzielenia się wiedzą, cierpliwość, tworzenie materiałów szkoleniowych i mentoring.',
    starHint: {
      situation: 'Nowy członek zespołu bez znajomości specyfiki projektów i procedur wewnętrznych.',
      task: 'Skrócenie czasu adaptacji do pełnej produktywności.',
      action: 'Przygotowanie planu pierwszych 30 dni, codzienne wsparcie (shadowing), feedback 1:1.',
      result: 'Nowy pracownik samodzielnie zrealizował pierwsze zadanie produkcyjne po 2 tygodniach.',
    },
    recommendedDurationSec: 60,
    tags: ['onboarding', 'mentoring', 'szkolenia'],
  },
  {
    id: 'prerecorded_l04',
    question: 'Jak zarządzasz oczekiwaniami sponsora projektu lub zarządu, gdy napotykasz nieprzewidziane przeszkody formalne lub budżetowe?',
    category: 'LEADERSHIP',
    intent: 'Bada transparentność komunikacji, wczesne ostrzeganie (no surprises) i przedstawianie rozwiązań, a nie tylko problemów.',
    starHint: {
      situation: 'Ryzyko przekroczenia budżetu lub terminu z przyczyn zewnętrznych.',
      task: 'Przedstawienie sytuacji decydentom przed wystąpieniem katastrofy.',
      action: 'Opracowanie raportu z 3 wariantami ratunkowymi i rekomendacją optymalnej ścieżki.',
      result: 'Zarząd zaakceptował rekomendowany wariant, projekt zachował płynność finansową.',
    },
    recommendedDurationSec: 60,
    tags: ['interesariusze', 'zarząd', 'raportowanie'],
  },
  {
    id: 'prerecorded_l05',
    question: 'Opowiedz o sytuacji, gdy musiałeś wyegzekwować przestrzeganie standardów jakościowych od pracownika, który próbował iść na skróty.',
    category: 'LEADERSHIP',
    intent: 'Bada konsekwencję menedżerską, umiejętność dawania konstruktywnego feedbacku (FUKO) i dbałość o kulturę odpowiedzialności.',
    starHint: {
      situation: 'Wykrycie, że członek zespołu omija procedury kontrolne, aby szybciej zamknąć zadanie.',
      task: 'Natychmiastowe zatrzymanie złej praktyki i uświadomienie ryzyk.',
      action: 'Rozmowa w cztery oczy w oparciu o fakty, wyznaczenie ponownej weryfikacji zadania.',
      result: 'Pracownik poprawił błędy, a standard jakości w zespole został obroniony.',
    },
    recommendedDurationSec: 60,
    tags: ['feedback', 'standardy', 'zarządzanie'],
  },
  {
    id: 'prerecorded_l06',
    question: 'Jak budujesz relacje i porozumienie z działami o zupełnie odmiennych celach (np. Sprzedaż vs Produkcja/IT)?',
    category: 'LEADERSHIP',
    intent: 'Bada myślenie ponad silosami organizacyjnymi, znajomość języka biznesu i szukanie wspólnego mianownika.',
    starHint: {
      situation: 'Rozbieżność celów: sprzedaż obiecała nierealny termin, a produkcja/IT wskazuje na brak mocy.',
      task: 'Wypracowanie wykonalnego planu bez wojny między działami.',
      action: 'Wspólny warsztat priorytetyzacji, rozbicie zakresu na MVP i etapy kolejne.',
      result: 'Zadowolony klient i brak przeciążenia zespołu operacyjnego.',
    },
    recommendedDurationSec: 60,
    tags: ['współpraca', 'silosy', 'komunikacja'],
  },
  {
    id: 'prerecorded_l07',
    question: 'Co robisz, aby utrzymać zaangażowanie i spokój w zespole podczas przedłużających się, stresujących wdrożeń?',
    category: 'LEADERSHIP',
    intent: 'Bada inteligencję emocjonalną, budowanie psychologicznego bezpieczeństwa i docenianie wkładu pracowników.',
    starHint: {
      situation: 'Wielotygodniowy okres wzmożonej pracy z ryzykiem wypalenia i rotacji.',
      task: 'Utrzymanie wysokiego morale i eliminacja zbędnych dystraktorów.',
      action: 'Ściąganie zbędnych spotkań z zespołu, regularne podziękowania za kamienie milowe, dbałość o regenerację.',
      result: 'Pomyślny finał wdrożenia przy zerowej rotacji i wysokiej satysfakcji zespołu.',
    },
    recommendedDurationSec: 60,
    tags: ['motywacja', 'morale', 'leadership'],
  },
];
