import { AudioManifest, AudioManifestItem } from './types';

export const RECRUITER_AUDIO_MANIFEST: AudioManifest = {
  manifest_version: '1.0',
  total_items: 180,
  items: [
    {
      id: 'A01',
      file: 'A/A01_najpowazniejszy_blad.mp3',
      category: 'QUEST_BEHAVIORAL',
      intent: 'Pytanie o dojrzałość, brak spychologii, proces opanowania krytycznej awarii i RCA.',
      transcript: 'Opowiedz o najpoważniejszym błędzie lub awarii, za którą odpowiadałeś, i jak krok po kroku opanowałeś sytuację.',
    },
    {
      id: 'A02',
      file: 'A/A02_decyzja_pod_presja.mp3',
      category: 'QUEST_BEHAVIORAL',
      intent: 'Pytanie o podejmowanie decyzji w warunkach niepewności i zarządzanie ryzykiem.',
      transcript: 'Opowiedz o sytuacji, gdy musiałeś podjąć kluczową decyzję techniczną lub operacyjną przy niepełnych danych i pod presją czasu.',
    },
    {
      id: 'A03',
      file: 'A/A03_mierzalny_sukces.mp3',
      category: 'QUEST_BEHAVIORAL',
      intent: 'Pytanie o nastawienie na twarde metryki biznesowe (ROI, KPI, czas, oszczędności).',
      transcript: 'Opowiedz o projekcie lub zadaniu, z którego wymiernych rezultatów liczbowych jesteś najbardziej dumny.',
    },
    {
      id: 'A04',
      file: 'A/A04_zmiana_priorytetow.mp3',
      category: 'QUEST_BEHAVIORAL',
      intent: 'Pytanie o elastyczność adaptacyjną i reakcję na nagłe przepakowanie zakresu prac.',
      transcript: 'Jak poradziłeś sobie z sytuacją, gdy w trakcie realizacji zadania diametralnie zmieniły się wymagania lub priorytety?',
    },
    {
      id: 'A05',
      file: 'A/A05_asertywnosc.mp3',
      category: 'QUEST_BEHAVIORAL',
      intent: 'Pytanie o asertywność techniczną i obronę standardów jakości wobec przełożonego/klienta.',
      transcript: 'Opowiedz o sytuacji, gdy musiałeś odmówić przełożonemu lub klientowi, zachowując asertywność techniczną lub biznesową.',
    },
    {
      id: 'A06',
      file: 'A/A06_optymalizacja_procesu.mp3',
      category: 'QUEST_BEHAVIORAL',
      intent: 'Pytanie o proaktywność, oddolne usprawnienia i eliminację marnotrawstwa (Lean/Kaizen).',
      transcript: 'Opowiedz o sytuacji, w której Twoja inicjatywa usprawniła powtarzalny proces w zespole lub firmie.',
    },
    {
      id: 'A07',
      file: 'A/A07_monotonia_detale.mp3',
      category: 'QUEST_BEHAVIORAL',
      intent: 'Pytanie o samodyscyplinę, checklisty i utrzymanie 100% dokładności w monotonnych zadaniach.',
      transcript: 'Jak radzisz sobie z monotonnymi lub wysoce powtarzalnymi zadaniami, które wymagają stuprocentowej dokładności?',
    },
    {
      id: 'A08',
      file: 'A/A08_lekcja_z_niepowodzenia.mp3',
      category: 'QUEST_BEHAVIORAL',
      intent: 'Pytanie o kulturę wyciągania wniosków z porażki i wdrażanie działań naprawczych.',
      transcript: 'Opowiedz o sytuacji, gdy projekt lub zadanie zakończyło się niepowodzeniem i czego Cię to nauczyło.',
    },
    {
      id: 'A09',
      file: 'A/A09_priorytetyzacja_pozarow.mp3',
      category: 'QUEST_BEHAVIORAL',
      intent: 'Pytanie o organizację pracy przy wielu równoległych pożarach (matryca Eisenhowera/Kanban).',
      transcript: 'W jaki sposób organizujesz swój dzień pracy, gdy masz do wykonania pięć pilnych zadań z różnych obszarów?',
    },
    {
      id: 'A10',
      file: 'A/A10_nieznany_problem.mp3',
      category: 'QUEST_BEHAVIORAL',
      intent: 'Pytanie o research, pracę z dokumentacją techniczną i rozwiązywanie problemów bez precedensu.',
      transcript: 'Co robisz, gdy napotykasz problem techniczny lub biznesowy, którego nigdy wcześniej nie rozwiązywałeś?',
    },
    {
      id: 'B01',
      file: 'B/B01_metodologia_rca.mp3',
      category: 'QUEST_TECHNICAL',
      intent: 'Pytanie o formalny proces lokalizacji usterki i metodologię Root Cause Analysis.',
      transcript: 'Jak przeprowadzasz proces diagnozy i lokalizacji usterki, gdy system lub maszyna nie działa prawidłowo?',
    },
    {
      id: 'B02',
      file: 'B/B02_dokumentacja_powykonawcza.mp3',
      category: 'QUEST_TECHNICAL',
      intent: 'Pytanie o dbałość o standardy dokumentacji technicznej, DTR i procedur powdrożeniowych.',
      transcript: 'W jaki sposób dbasz o jakość dokumentacji technicznej i procedur w swoich projektach?',
    },
    {
      id: 'B03',
      file: 'B/B03_kompromis_architektoniczny.mp3',
      category: 'QUEST_TECHNICAL',
      intent: 'Pytanie o świadome zaciąganie długu technicznego ze względu na budżet lub czas.',
      transcript: 'Opowiedz o kompromisie architektonicznym lub technologicznym, na który musiałeś pójść ze względu na budżet lub czas.',
    },
    {
      id: 'B04',
      file: 'B/B04_kontrola_odbiorcza_qa.mp3',
      category: 'QUEST_TECHNICAL',
      intent: 'Pytanie o mechanizmy kontroli jakości (QA/QC) i weryfikację przed odbiorem.',
      transcript: 'Jakie mechanizmy kontroli jakości stosujesz przed przekazaniem pracy do odbioru?',
    },
    {
      id: 'B05',
      file: 'B/B05_cyberbezpieczenstwo_rodo.mp3',
      category: 'QUEST_TECHNICAL',
      intent: 'Pytanie o higienę bezpieczeństwa IT, ochronę tajemnicy przedsiębiorstwa i dane poufne.',
      transcript: 'Jakie zasady cyberbezpieczeństwa lub ochrony danych poufnych stosujesz na co dzień?',
    },
    {
      id: 'B06',
      file: 'B/B06_optymalizacja_wydajnosci.mp3',
      category: 'QUEST_TECHNICAL',
      intent: 'Pytanie o profilowanie, redukcję zużycia zasobów i optymalizację cyklu pracy.',
      transcript: 'W jaki sposób optymalizujesz wydajność i zużycie zasobów, takich jak czas cyklu, zapytania czy zużycie energii i materiałów?',
    },
    {
      id: 'B07',
      file: 'B/B07_automatyzacja_zadan.mp3',
      category: 'QUEST_TECHNICAL',
      intent: 'Pytanie o identyfikację i automatyzację powtarzalnych procesów technicznych/operacyjnych.',
      transcript: 'Jak podchodzisz do automatyzacji powtarzalnych zadań w swoim środowisku pracy?',
    },
    {
      id: 'B08',
      file: 'B/B08_niekompatybilne_systemy.mp3',
      category: 'QUEST_TECHNICAL',
      intent: 'Pytanie o integrację odmiennych standardów, protokołów lub urządzeń (legacy/heterogeneous).',
      transcript: 'Opowiedz o sytuacji, gdy musiałeś zintegrować dwa zupełnie różne systemy lub urządzenia, które domyślnie ze sobą nie współpracowały.',
    },
    {
      id: 'B09',
      file: 'B/B09_monitoring_sla.mp3',
      category: 'QUEST_TECHNICAL',
      intent: 'Pytanie o proaktywny monitoring metryk produkcyjnych i zapobieganie naruszeniom SLA.',
      transcript: 'W jaki sposób monitorujesz stan środowiska produkcyjnego lub operacyjnego, aby zapobiegać awariom, zanim zauważy je użytkownik?',
    },
    {
      id: 'B10',
      file: 'B/B10_zero_downtime.mp3',
      category: 'QUEST_TECHNICAL',
      intent: 'Pytanie o procedury serwisowe i wdrażanie zmian w reżimie ciągłej pracy (Zero Downtime).',
      transcript: 'Jak postępujesz w przypadku konieczności wykonania prac serwisowych w środowisku pracującym pod ciągłym obciążeniem?',
    },
    {
      id: 'C01',
      file: 'C/C01_bhp_zagrozenie.mp3',
      category: 'QUEST_SPECIALIST',
      intent: 'Pytanie o reakcję na bezpośrednie zagrożenie wypadkowe i egzekwowanie BHP/SEP/UDT.',
      transcript: 'Opowiedz o sytuacji, w której warunki na stanowisku pracy stwarzały bezpośrednie zagrożenie wypadkiem i jak na to zareagowałeś.',
    },
    {
      id: 'C02',
      file: 'C/C02_hvac_pompy_kotly.mp3',
      category: 'QUEST_SPECIALIST',
      intent: 'Pytanie o procedurę rozruchu, próby ciśnieniowe i analizę spalin w technice grzewczej HVAC.',
      transcript: 'W jaki sposób przeprowadzasz protokół prób szczelności i analizy spalin przy pierwszym uruchomieniu kotła gazowego lub pompy ciepła?',
    },
    {
      id: 'C03',
      file: 'C/C03_spawalnictwo_tig_mag.mp3',
      category: 'QUEST_SPECIALIST',
      intent: 'Pytanie o parametry spawalnicze TIG/MAG i przygotowanie spoiny pod badania nieniszczące VT2/RTG.',
      transcript: 'Jak dobierasz parametry spawania metodą TIG lub MAG i przygotowujesz złącze, aby bez problemu przejść badania wizualne oraz radiograficzne?',
    },
    {
      id: 'C04',
      file: 'C/C04_elektryka_rozdzielnice_nn.mp3',
      category: 'QUEST_SPECIALIST',
      intent: 'Pytanie o montaż szaf nn oraz procedurę pomiarów odbiorczych (impedancja pętli, RCD, rezystancja izolacji).',
      transcript: 'Opowiedz o procesie prefabrykacji lub modernizacji szafy rozdzielczej niskiego napięcia i jak wykonujesz pomiary odbiorcze miernikiem wielofunkcyjnym?',
    },
    {
      id: 'C05',
      file: 'C/C05_logistyka_magazyn_wysoki.mp3',
      category: 'QUEST_SPECIALIST',
      intent: 'Pytanie o logistykę magazynową, koordynację ruchu wózków UDT i bezpieczeństwo kompletacji.',
      transcript: 'Jak organizujesz bezpieczną i wydajną kompletację zamówień w magazynie wysokiego składowania przy jednoczesnym rozładunku dostaw i pracy wózków widłowych?',
    },
    {
      id: 'C06',
      file: 'C/C06_transport_aetr_ce.mp3',
      category: 'QUEST_SPECIALIST',
      intent: 'Pytanie o zarządzanie czasem pracy kierowcy AETR i mocowanie ładunku w sytuacjach awaryjnych.',
      transcript: 'W jaki sposób zarządzasz czasem jazdy i odpoczynku oraz zabezpieczeniem ładunku pasami, gdy na trasie pojawiają się nieprzewidziane zatory drogowe?',
    },
    {
      id: 'C07',
      file: 'C/C07_cnc_tolerancje_iso.mp3',
      category: 'QUEST_SPECIALIST',
      intent: 'Pytanie o obróbkę skrawaniem CNC, bazowanie detalu, korekcje narzędziowe i weryfikację G-code.',
      transcript: 'Jak przygotowujesz i ustawiasz detal na obrabiarce CNC oraz weryfikujesz kod G-code i korekcje narzędzi, aby uniknąć kolizji i braków?',
    },
    {
      id: 'C08',
      file: 'C/C08_medycyna_triage.mp3',
      category: 'QUEST_SPECIALIST',
      intent: 'Pytanie o postępowanie w stanach nagłych, procedury segregacji medycznej triage i reżim sanitarny.',
      transcript: 'Opowiedz o postępowaniu w nagłym pogorszeniu stanu pacjenta lub procedurze triage i jak zapewniasz rygorystyczne przestrzeganie procedur sanitarno-epidemiologicznych?',
    },
    {
      id: 'D01',
      file: 'D/D01_konflikt_w_zespole.mp3',
      category: 'QUEST_LEADERSHIP',
      intent: 'Pytanie o mediację, rozwiązywanie konfliktów personalnych i ochronę terminu projektu.',
      transcript: 'Jak poradziłeś sobie z konfliktem personalnym lub merytorycznym w zespole, który zagrażał terminowi realizacji projektu?',
    },
    {
      id: 'D02',
      file: 'D/D02_niezadowolony_klient.mp3',
      category: 'QUEST_LEADERSHIP',
      intent: 'Pytanie o deeskalację emocji, negocjacje reklamacyjne i ratowanie relacji z klientem.',
      transcript: 'Opowiedz o trudnych negocjacjach lub rozmowie z niezadowolonym klientem, który chciał zerwać umowę lub zgłosił poważną reklamację.',
    },
    {
      id: 'D03',
      file: 'D/D03_onboarding_pracownika.mp3',
      category: 'QUEST_LEADERSHIP',
      intent: 'Pytanie o strukturę wdrażania nowych osób i skracanie czasu dojścia do samodzielności (time-to-productivity).',
      transcript: 'W jaki sposób wprowadzasz i szkolisz nowego pracownika, aby szybko stał się w pełni samodzielny?',
    },
    {
      id: 'D04',
      file: 'D/D04_zarzadzanie_oczekiwaniami.mp3',
      category: 'QUEST_LEADERSHIP',
      intent: 'Pytanie o transparentną komunikację w górę (stakeholder management) przy ryzyku budżetowym/terminowym.',
      transcript: 'Jak zarządzasz oczekiwaniami sponsora projektu lub zarządu, gdy napotykasz nieprzewidziane przeszkody formalne lub budżetowe?',
    },
    {
      id: 'D05',
      file: 'D/D05_egzekwowanie_jakosci.mp3',
      category: 'QUEST_LEADERSHIP',
      intent: 'Pytanie o feedback korygujący i zatrzymywanie chodzenia na skróty w zespole.',
      transcript: 'Opowiedz o sytuacji, gdy musiałeś wyegzekwować przestrzeganie standardów jakościowych od pracownika, który próbował iść na skróty.',
    },
    {
      id: 'D06',
      file: 'D/D06_przelamywanie_silosow.mp3',
      category: 'QUEST_LEADERSHIP',
      intent: 'Pytanie o współpracę międzyfunkcyjną i eliminację tarć między odrębnymi departamentami.',
      transcript: 'Jak budujesz relacje i porozumienie z działami o zupełnie odmiennych celach, na przykład między sprzedażą a produkcją lub IT?',
    },
    {
      id: 'D07',
      file: 'D/D07_morale_przy_wdrozeniach.mp3',
      category: 'QUEST_LEADERSHIP',
      intent: 'Pytanie o przeciwdziałanie wypaleniu i utrzymanie stabilności zespołu pod długotrwałą presją.',
      transcript: 'Co robisz, aby utrzymać zaangażowanie i spokój w zespole podczas przedłużających się, stresujących wdrożeń?',
    },
    {
      id: 'ACK_01',
      file: 'ACK/ACK_01_rozumiem.mp3',
      category: 'FILLER_ACK',
      intent: 'Potwierdzenie zrozumienia wypowiedzi.',
      transcript: 'Rozumiem.',
    },
    {
      id: 'ACK_02',
      file: 'ACK/ACK_02_aha.mp3',
      category: 'FILLER_ACK',
      intent: 'Krótki wtręt aktywnego słuchania.',
      transcript: 'Aha.',
    },
    {
      id: 'ACK_03',
      file: 'ACK/ACK_03_jasne.mp3',
      category: 'FILLER_ACK',
      intent: 'Aprobata i jasność sytuacji.',
      transcript: 'Jasne.',
    },
    {
      id: 'ACK_04',
      file: 'ACK/ACK_04_mhm.mp3',
      category: 'FILLER_ACK',
      intent: 'Dźwiękowe potwierdzenie uwagi w trakcie mówienia użytkownika.',
      transcript: 'Mhm.',
    },
    {
      id: 'ACK_05',
      file: 'ACK/ACK_05_yhm.mp3',
      category: 'FILLER_ACK',
      intent: 'Naturalny pomruk aktywnego słuchania.',
      transcript: 'Yhm.',
    },
    {
      id: 'ACK_06',
      file: 'ACK/ACK_06_dokladnie.mp3',
      category: 'FILLER_ACK',
      intent: 'Mocne potwierdzenie tezy rozmówcy.',
      transcript: 'Dokładnie.',
    },
    {
      id: 'ACK_07',
      file: 'ACK/ACK_07_oczywiscie.mp3',
      category: 'FILLER_ACK',
      intent: 'Potwierdzenie oczywistego faktu.',
      transcript: 'Oczywiście.',
    },
    {
      id: 'ACK_08',
      file: 'ACK/ACK_08_w_porzadku.mp3',
      category: 'FILLER_ACK',
      intent: 'Akceptacja przedstawionej informacji.',
      transcript: 'W porządku.',
    },
    {
      id: 'ACK_09',
      file: 'ACK/ACK_09_dobrze.mp3',
      category: 'FILLER_ACK',
      intent: 'Neutralne odnotowanie punktu.',
      transcript: 'Dobrze.',
    },
    {
      id: 'ACK_10',
      file: 'ACK/ACK_10_tak_jest.mp3',
      category: 'FILLER_ACK',
      intent: 'Formalne potwierdzenie stanu rzeczy.',
      transcript: 'Tak jest.',
    },
    {
      id: 'ACK_11',
      file: 'ACK/ACK_11_zgoda.mp3',
      category: 'FILLER_ACK',
      intent: 'Wyrażenie pełnej zgody z wnioskiem.',
      transcript: 'Zgoda.',
    },
    {
      id: 'ACK_12',
      file: 'ACK/ACK_12_no_tak.mp3',
      category: 'FILLER_ACK',
      intent: 'Potoczne, naturalne przytaknięcie.',
      transcript: 'No tak.',
    },
    {
      id: 'ACK_13',
      file: 'ACK/ACK_13_wlasnie.mp3',
      category: 'FILLER_ACK',
      intent: 'Potwierdzenie trafności uwagi.',
      transcript: 'Właśnie.',
    },
    {
      id: 'ACK_14',
      file: 'ACK/ACK_14_dokladnie_tak.mp3',
      category: 'FILLER_ACK',
      intent: 'Podwójne potwierdzenie merytoryczne.',
      transcript: 'Dokładnie tak.',
    },
    {
      id: 'ACK_15',
      file: 'ACK/ACK_15_jasna_sprawa.mp3',
      category: 'FILLER_ACK',
      intent: 'Potoczne potwierdzenie pełnego zrozumienia.',
      transcript: 'Jasna sprawa.',
    },
    {
      id: 'ACK_16',
      file: 'ACK/ACK_16_zrozumiale.mp3',
      category: 'FILLER_ACK',
      intent: 'Zasygnalizowanie logiczności wywodu.',
      transcript: 'Zrozumiałe.',
    },
    {
      id: 'ACK_17',
      file: 'ACK/ACK_17_jak_najbardziej.mp3',
      category: 'FILLER_ACK',
      intent: 'Mocna walidacja poprawności postępowania.',
      transcript: 'Jak najbardziej.',
    },
    {
      id: 'ACK_18',
      file: 'ACK/ACK_18_to_ma_sens.mp3',
      category: 'FILLER_ACK',
      intent: 'Walidacja sensu logicznego argumentu.',
      transcript: 'To ma sens.',
    },
    {
      id: 'ACK_19',
      file: 'ACK/ACK_19_sluszna_uwaga.mp3',
      category: 'FILLER_ACK',
      intent: 'Uznanie merytorycznego wkładu rozmówcy.',
      transcript: 'Słuszna uwaga.',
    },
    {
      id: 'ACK_20',
      file: 'ACK/ACK_20_rozumiem_kontekst.mp3',
      category: 'FILLER_ACK',
      intent: 'Potwierdzenie zrozumienia tła sytuacyjnego.',
      transcript: 'Rozumiem kontekst.',
    },
    {
      id: 'ACK_21',
      file: 'ACK/ACK_21_wiem_o_co_chodzi.mp3',
      category: 'FILLER_ACK',
      intent: 'Szybkie potoczne złapanie intencji.',
      transcript: 'Wiem, o co chodzi.',
    },
    {
      id: 'ACK_22',
      file: 'ACK/ACK_22_pelen_obraz.mp3',
      category: 'FILLER_ACK',
      intent: 'Zasygnalizowanie, że sytuacja jest kompletna informacyjnie.',
      transcript: 'Mam pełen obraz.',
    },
    {
      id: 'ACK_23',
      file: 'ACK/ACK_23_przyjalem.mp3',
      category: 'FILLER_ACK',
      intent: 'Krótkie operacyjne odnotowanie.',
      transcript: 'Przyjąłem.',
    },
    {
      id: 'ACK_24',
      file: 'ACK/ACK_24_okej.mp3',
      category: 'FILLER_ACK',
      intent: 'Krótki, neutralny łącznik audio.',
      transcript: 'Okej.',
    },
    {
      id: 'ACK_25',
      file: 'ACK/ACK_25_wszystko_jasne.mp3',
      category: 'FILLER_ACK',
      intent: 'Końcowe potwierdzenie braku wątpliwości.',
      transcript: 'Wszystko jasne.',
    },
    {
      id: 'THK_01',
      file: 'THK/THK_01_hmm.mp3',
      category: 'FILLER_THINK',
      intent: 'Dźwięk namysłu (maskowanie opóźnienia 1-2s).',
      transcript: 'Hmm...',
    },
    {
      id: 'THK_02',
      file: 'THK/THK_02_no_dobrze.mp3',
      category: 'FILLER_THINK',
      intent: 'Pauza przed przejściem do analizy.',
      transcript: 'No dobrze...',
    },
    {
      id: 'THK_03',
      file: 'THK/THK_03_dobre_pytanie.mp3',
      category: 'FILLER_THINK',
      intent: 'Pozytywny bufor czasowy przed odpowiedzią.',
      transcript: 'Dobre pytanie...',
    },
    {
      id: 'THK_04',
      file: 'THK/THK_04_ciekawe_podejscie.mp3',
      category: 'FILLER_THINK',
      intent: 'Reakcja na niestandardowe rozwiązanie.',
      transcript: 'Ciekawe podejście...',
    },
    {
      id: 'THK_05',
      file: 'THK/THK_05_chwileczke.mp3',
      category: 'FILLER_THINK',
      intent: 'Krótka pauza na weryfikację danych.',
      transcript: 'Chwileczkę...',
    },
    {
      id: 'THK_06',
      file: 'THK/THK_06_spojrzmy_na_to.mp3',
      category: 'FILLER_THINK',
      intent: 'Wprowadzenie do głębszej analizy problemu.',
      transcript: 'Spójrzmy na to...',
    },
    {
      id: 'THK_07',
      file: 'THK/THK_07_no_coz.mp3',
      category: 'FILLER_THINK',
      intent: 'Pauza z lekkim westchnieniem/refleksją.',
      transcript: 'No cóż...',
    },
    {
      id: 'THK_08',
      file: 'THK/THK_08_pomyslmy.mp3',
      category: 'FILLER_THINK',
      intent: 'Zasygnalizowanie wejścia w tryb kalkulacji/namysłu.',
      transcript: 'Pomyślmy...',
    },
    {
      id: 'THK_09',
      file: 'THK/THK_09_zastanowmy_sie.mp3',
      category: 'FILLER_THINK',
      intent: 'Pauza angażująca uwagę rozmówcy.',
      transcript: 'Zastanówmy się...',
    },
    {
      id: 'THK_10',
      file: 'THK/THK_10_wiesz_co.mp3',
      category: 'FILLER_THINK',
      intent: 'Kolokwialna pauza przed nagłą zmianą myśli.',
      transcript: 'Wiesz co...',
    },
    {
      id: 'THK_11',
      file: 'THK/THK_11_rzucmy_okiem.mp3',
      category: 'FILLER_THINK',
      intent: 'Przejście do analizy wycinka problemu.',
      transcript: 'Rzućmy na to okiem...',
    },
    {
      id: 'THK_12',
      file: 'THK/THK_12_zaraz_zobaczymy.mp3',
      category: 'FILLER_THINK',
      intent: 'Bufor oczekiwania na przetwarzanie.',
      transcript: 'Zaraz zobaczymy...',
    },
    {
      id: 'THK_13',
      file: 'THK/THK_13_ciekawy_punkt.mp3',
      category: 'FILLER_THINK',
      intent: 'Odnotowanie specyficznego punktu widzenia.',
      transcript: 'Ciekawy punkt widzenia...',
    },
    {
      id: 'THK_14',
      file: 'THK/THK_14_wezmy_to_pod_uwage.mp3',
      category: 'FILLER_THINK',
      intent: 'Zapisanie czynnika do pamięci roboczej.',
      transcript: 'Weźmy to pod uwagę...',
    },
    {
      id: 'THK_15',
      file: 'THK/THK_15_zaraz_to_przeanalizujemy.mp3',
      category: 'FILLER_THINK',
      intent: 'Zapowiedź szczegółowej weryfikacji.',
      transcript: 'Zaraz to przeanalizujemy...',
    },
    {
      id: 'CONT_01',
      file: 'CONT/CONT_01_mow_dalej.mp3',
      category: 'FILLER_CONTINUE',
      intent: 'Krótka zachęta do kontynuacji monologu.',
      transcript: 'Mów dalej.',
    },
    {
      id: 'CONT_02',
      file: 'CONT/CONT_02_slucham_dalej.mp3',
      category: 'FILLER_CONTINUE',
      intent: 'Sygnał utrzymywania uwagi na wątku.',
      transcript: 'Słucham dalej.',
    },
    {
      id: 'CONT_03',
      file: 'CONT/CONT_03_kontynuuj_prosze.mp3',
      category: 'FILLER_CONTINUE',
      intent: 'Uprzejma prośba o dokończenie myśli.',
      transcript: 'Kontynuuj, proszę.',
    },
    {
      id: 'CONT_04',
      file: 'CONT/CONT_04_co_bylo_dalej.mp3',
      category: 'FILLER_CONTINUE',
      intent: 'Dopytanie o chronologiczny ciąg zdarzeń.',
      transcript: 'I co było dalej?',
    },
    {
      id: 'CONT_05',
      file: 'CONT/CONT_05_jak_to_sie_skonczylo.mp3',
      category: 'FILLER_CONTINUE',
      intent: 'Dopytanie o ostateczny rezultat akcji.',
      transcript: 'Jak to się skończyło?',
    },
    {
      id: 'CONT_06',
      file: 'CONT/CONT_06_rozwin_to.mp3',
      category: 'FILLER_CONTINUE',
      intent: 'Prośba o podanie większej liczby szczegółów.',
      transcript: 'Rozwiń to, proszę.',
    },
    {
      id: 'CONT_07',
      file: 'CONT/CONT_07_opowiedz_wiecej.mp3',
      category: 'FILLER_CONTINUE',
      intent: 'Zachęta do pogłębienia opisu sytuacji.',
      transcript: 'Opowiedz coś więcej.',
    },
    {
      id: 'CONT_08',
      file: 'CONT/CONT_08_co_bylo_potem.mp3',
      category: 'FILLER_CONTINUE',
      intent: 'Prośba o opis kolejnego etapu po kluczowym wydarzeniu.',
      transcript: 'Co było potem?',
    },
    {
      id: 'CONT_09',
      file: 'CONT/CONT_09_i_co_wtedy.mp3',
      category: 'FILLER_CONTINUE',
      intent: 'Dopytanie o bezpośrednią reakcję w punkcie zwrotnym.',
      transcript: 'I co wtedy zrobiłeś?',
    },
    {
      id: 'CONT_10',
      file: 'CONT/CONT_10_jak_w_praktyce.mp3',
      category: 'FILLER_CONTINUE',
      intent: 'Przejście z teorii na wykonanie operacyjne.',
      transcript: 'Jak to wyglądało w praktyce?',
    },
    {
      id: 'CONT_11',
      file: 'CONT/CONT_11_slucham_uwaznie.mp3',
      category: 'FILLER_CONTINUE',
      intent: 'Zapewnienie o pełnym skupieniu na technicznym opisie.',
      transcript: 'Słucham uważnie.',
    },
    {
      id: 'CONT_12',
      file: 'CONT/CONT_12_a_szczegoly.mp3',
      category: 'FILLER_CONTINUE',
      intent: 'Dopytanie o detale implementacyjne/konfiguracyjne.',
      transcript: 'A jak wyglądały szczegóły?',
    },
    {
      id: 'CONT_13',
      file: 'CONT/CONT_13_jasne_i_co_dalej.mp3',
      category: 'FILLER_CONTINUE',
      intent: 'Zrozumienie bieżącego kroku i pchnięcie rozmowy do przodu.',
      transcript: 'Jasne, i co dalej?',
    },
    {
      id: 'CONT_14',
      file: 'CONT/CONT_14_jak_zareagowales.mp3',
      category: 'FILLER_CONTINUE',
      intent: 'Dopytanie o zachowanie kandydata w obliczu zmiany sytuacji.',
      transcript: 'I jak na to zareagowałeś?',
    },
    {
      id: 'CONT_15',
      file: 'CONT/CONT_15_jak_to_rozwiazales.mp3',
      category: 'FILLER_CONTINUE',
      intent: 'Wymuszenie przejścia do etapu rozwiązania (Action).',
      transcript: 'W jaki sposób to rozwiązałeś?',
    },
    {
      id: 'RCT_01',
      file: 'RCT/RCT_01_trudna_sytuacja.mp3',
      category: 'FILLER_REACTION',
      intent: 'Empatyczna walidacja trudnego incydentu produkcyjnego.',
      transcript: 'Brzmi jak trudna sytuacja.',
    },
    {
      id: 'RCT_02',
      file: 'RCT/RCT_02_powazny_temat.mp3',
      category: 'FILLER_REACTION',
      intent: 'Podkreślenie wagi i krytyczności opisywanej awarii.',
      transcript: 'To brzmi poważnie.',
    },
    {
      id: 'RCT_03',
      file: 'RCT/RCT_03_spore_wyzwanie.mp3',
      category: 'FILLER_REACTION',
      intent: 'Uznanie złożoności technicznej problemu.',
      transcript: 'Rzeczywiście, spore wyzwanie.',
    },
    {
      id: 'RCT_04',
      file: 'RCT/RCT_04_wymagajace.mp3',
      category: 'FILLER_REACTION',
      intent: 'Walidacja wysiłku włożonego w realizację zadania.',
      transcript: 'To musiało być wymagające.',
    },
    {
      id: 'RCT_05',
      file: 'RCT/RCT_05_wyobrazam_sobie.mp3',
      category: 'FILLER_REACTION',
      intent: 'Zrozumienie poziomu stresu lub presji.',
      transcript: 'Wyobrażam sobie.',
    },
    {
      id: 'RCT_06',
      file: 'RCT/RCT_06_niezly_pozar.mp3',
      category: 'FILLER_REACTION',
      intent: 'Potoczne podsumowanie gaszenia nagłego incydentu.',
      transcript: 'Niezły pożar do ugaszenia.',
    },
    {
      id: 'RCT_07',
      file: 'RCT/RCT_07_presja_czasu.mp3',
      category: 'FILLER_REACTION',
      intent: 'Reakcja na pracę pod napiętym deadline\'em.',
      transcript: 'Rozumiem tę presję.',
    },
    {
      id: 'RCT_08',
      file: 'RCT/RCT_08_klasyczny_problem.mp3',
      category: 'FILLER_REACTION',
      intent: 'Odnotowanie typowego, podręcznikowego błędu systemowego.',
      transcript: 'Klasyczny problem.',
    },
    {
      id: 'RCT_09',
      file: 'RCT/RCT_09_niezla_przeprawa.mp3',
      category: 'FILLER_REACTION',
      intent: 'Reakcja na żmudny, wieloetapowy proces naprawczy.',
      transcript: 'Niezła przeprawa.',
    },
    {
      id: 'RCT_10',
      file: 'RCT/RCT_10_swietny_wynik.mp3',
      category: 'FILLER_REACTION',
      intent: 'Pozytywna ocena mierzalnego sukcesu/metryki.',
      transcript: 'Świetny wynik.',
    },
    {
      id: 'RCT_11',
      file: 'RCT/RCT_11_bardzo_dobrze.mp3',
      category: 'FILLER_REACTION',
      intent: 'Pochwała poprawnej decyzji architektonicznej.',
      transcript: 'Bardzo dobrze to rozegrałeś.',
    },
    {
      id: 'RCT_12',
      file: 'RCT/RCT_12_robi_wrazenie.mp3',
      category: 'FILLER_REACTION',
      intent: 'Uznanie dla skali projektu lub wysokich oszczędności.',
      transcript: 'Robi wrażenie.',
    },
    {
      id: 'RCT_13',
      file: 'RCT/RCT_13_niecodzienna_sprawa.mp3',
      category: 'FILLER_REACTION',
      intent: 'Reakcja na rzadki przypadek brzegowy (edge case).',
      transcript: 'Niecodzienna sprawa.',
    },
    {
      id: 'RCT_14',
      file: 'RCT/RCT_14_czesty_blad.mp3',
      category: 'FILLER_REACTION',
      intent: 'Walidacja błędu jako typowego potknięcia branżowego.',
      transcript: 'To częsty błąd w takich projektach.',
    },
    {
      id: 'RCT_15',
      file: 'RCT/RCT_15_w_pelni_rozumiem.mp3',
      category: 'FILLER_REACTION',
      intent: 'Całkowite utożsamienie się z decyzją rozmówcy.',
      transcript: 'W pełni to rozumiem.',
    },
    {
      id: 'TRS_01',
      file: 'TRS/TRS_01_idzmy_dalej.mp3',
      category: 'FILLER_TRANSITION',
      intent: 'Zamknięcie bieżącego wątku i ruch do przodu.',
      transcript: 'W porządku, idźmy dalej.',
    },
    {
      id: 'TRS_02',
      file: 'TRS/TRS_02_przejdzmy_dalej.mp3',
      category: 'FILLER_TRANSITION',
      intent: 'Formalne przejście do kolejnego punktu agendy.',
      transcript: 'Dobrze, przejdźmy do kolejnej kwestii.',
    },
    {
      id: 'TRS_03',
      file: 'TRS/TRS_03_to_mamy_omowione.mp3',
      category: 'FILLER_TRANSITION',
      intent: 'Odznaczenie pytania jako w pełni wyczerpanego.',
      transcript: 'To mamy omówione.',
    },
    {
      id: 'TRS_04',
      file: 'TRS/TRS_04_skupmy_sie_na_tym.mp3',
      category: 'FILLER_TRANSITION',
      intent: 'Przekierowanie uwagi na nowy problem.',
      transcript: 'Skupmy się teraz na tym.',
    },
    {
      id: 'TRS_05',
      file: 'TRS/TRS_05_wiele_wyjasnia.mp3',
      category: 'FILLER_TRANSITION',
      intent: 'Podsumowanie wyjaśnienia i przygotowanie pod nowe pytanie.',
      transcript: 'To wiele wyjaśnia.',
    },
    {
      id: 'TRS_06',
      file: 'TRS/TRS_06_zamykamy_watek.mp3',
      category: 'FILLER_TRANSITION',
      intent: 'Definitywne zamknięcie dyskusji nad danym casem.',
      transcript: 'Dobrze, zamykamy ten wątek.',
    },
    {
      id: 'TRS_07',
      file: 'TRS/TRS_07_druga_kwestia.mp3',
      category: 'FILLER_TRANSITION',
      intent: 'Otwarcie powiązanego pytania uzupełniającego.',
      transcript: 'A jak wygląda druga kwestia?',
    },
    {
      id: 'TRS_08',
      file: 'TRS/TRS_08_wrocmy_do_sedna.mp3',
      category: 'FILLER_TRANSITION',
      intent: 'Ukierunkowanie po dygresji z powrotem na główny temat.',
      transcript: 'Wróćmy do sedna.',
    },
    {
      id: 'TRS_09',
      file: 'TRS/TRS_09_sprawdzmy_kolejna_rzecz.mp3',
      category: 'FILLER_TRANSITION',
      intent: 'Zapowiedź weryfikacji nowego obszaru kompetencji.',
      transcript: 'Sprawdźmy kolejną rzecz.',
    },
    {
      id: 'TRS_10',
      file: 'TRS/TRS_10_mamy_to.mp3',
      category: 'FILLER_TRANSITION',
      intent: 'Krótkie potoczne podsumowanie zaliczonego zagadnienia.',
      transcript: 'Dobra, to mamy ustalone.',
    },
    {
      id: 'TRS_11',
      file: 'TRS/TRS_11_kolejny_krok.mp3',
      category: 'FILLER_TRANSITION',
      intent: 'Płynne przejście do następnego etapu schematu wywiadu.',
      transcript: 'Przejdźmy do następnego kroku.',
    },
    {
      id: 'TRS_12',
      file: 'TRS/TRS_12_zmieniajac_temat.mp3',
      category: 'FILLER_TRANSITION',
      intent: 'Sygnał zmiany kategorii pytań (np. z technicznych na leadership).',
      transcript: 'Zmieniając nieco temat...',
    },
    {
      id: 'TRS_13',
      file: 'TRS/TRS_13_podsumowujac_ten_punkt.mp3',
      category: 'FILLER_TRANSITION',
      intent: 'Wprowadzenie do klamry kompozycyjnej danego bloku.',
      transcript: 'Podsumowując ten punkt...',
    },
    {
      id: 'TRS_14',
      file: 'TRS/TRS_14_kolejny_aspekt.mp3',
      category: 'FILLER_TRANSITION',
      intent: 'Rozszerzenie kontekstu o kolejny wymiar problemu.',
      transcript: 'Spójrzmy na kolejny aspekt.',
    },
    {
      id: 'TRS_15',
      file: 'TRS/TRS_15_to_teraz_inna_sprawa.mp3',
      category: 'FILLER_TRANSITION',
      intent: 'Kontrastowe przejście do zupełnie innego zagadnienia.',
      transcript: 'To teraz nieco inna sprawa.',
    },
    {
      id: 'CLR_01',
      file: 'CLR/CLR_01_star_rola.mp3',
      category: 'DRILL_STAR',
      intent: 'Wyodrębnienie indywidualnego wkładu kandydata od pracy reszty zespołu.',
      transcript: 'A jaka w tym wszystkim była dokładnie Twoja rola, a co robił zespół?',
    },
    {
      id: 'CLR_02',
      file: 'CLR/CLR_02_star_liczby.mp3',
      category: 'DRILL_STAR',
      intent: 'Wymuszenie podania twardych danych liczbowych, skali i metryk.',
      transcript: 'Możesz podać jakieś konkretne liczby, procenty albo skale tego projektu?',
    },
    {
      id: 'CLR_03',
      file: 'CLR/CLR_03_star_alternatywa.mp3',
      category: 'DRILL_STAR',
      intent: 'Weryfikacja procesu decyzyjnego i odrzuconych opcji (trade-offs).',
      transcript: 'Jakie inne rozwiązania brałeś wtedy pod uwagę i dlaczego z nich zrezygnowałeś?',
    },
    {
      id: 'CLR_04',
      file: 'CLR/CLR_04_star_waski_gardziel.mp3',
      category: 'DRILL_STAR',
      intent: 'Lokalizacja wąskich gardeł technologicznych lub ludzkich.',
      transcript: 'Gdzie w tym całym procesie pojawiło się największe wąskie gardło?',
    },
    {
      id: 'CLR_05',
      file: 'CLR/CLR_05_star_blad_wlasny.mp3',
      category: 'DRILL_STAR',
      intent: 'Ocena samokrytycyzmu i wyciągania wniosków ex-post.',
      transcript: 'Czy patrząc na to z perspektywy czasu, zrobiłbyś coś inaczej?',
    },
    {
      id: 'CLR_06',
      file: 'CLR/CLR_06_star_narzedzia.mp3',
      category: 'DRILL_STAR',
      intent: 'Dopytanie o konkretny stack technologiczny, biblioteki i narzędzia.',
      transcript: 'Jakich konkretnie narzędzi i technologii użyliście do rozwiązania tego problemu?',
    },
    {
      id: 'CLR_07',
      file: 'CLR/CLR_07_star_czas.mp3',
      category: 'DRILL_STAR',
      intent: 'Weryfikacja czasu reakcji i MTTR (Mean Time to Resolution).',
      transcript: 'Ile czasu zajęło Wam dojście do stabilnego rozwiązania od momentu wykrycia błędu?',
    },
    {
      id: 'CLR_08',
      file: 'CLR/CLR_08_star_budzet.mp3',
      category: 'DRILL_STAR',
      intent: 'Sprawdzenie dyscypliny budżetowej i harmonogramowej.',
      transcript: 'Czy zmieściliście się w pierwotnym budżecie i harmonogramie?',
    },
    {
      id: 'CLR_09',
      file: 'CLR/CLR_09_star_kto_zauwazyl.mp3',
      category: 'DRILL_STAR',
      intent: 'Weryfikacja monitoringu (czy był alert, czy zgłoszenie od klienta).',
      transcript: 'Kto pierwszy zauważył, że coś poszło nie tak: Wy czy klient?',
    },
    {
      id: 'CLR_10',
      file: 'CLR/CLR_10_star_postmortem.mp3',
      category: 'DRILL_STAR',
      intent: 'Weryfikacja kultury post-mortem i formalizacji bazy wiedzy.',
      transcript: 'Czy po wszystkim przeprowadziliście formalne post-mortem i spisaliście wnioski?',
    },
    {
      id: 'DBT_01',
      file: 'DBT/DBT_01_zbyt_ogolnie.mp3',
      category: 'DRILL_SKEPTIC',
      intent: 'Zatrzymanie ogólnikowych deklaracji i żądanie konkretnego przykładu.',
      transcript: 'Brzmi to dość ogólnie. Opowiedz o jednym, bardzo konkretnym przypadku.',
    },
    {
      id: 'DBT_02',
      file: 'DBT/DBT_02_za_prosto.mp3',
      category: 'DRILL_SKEPTIC',
      intent: 'Konfrontacja z podejrzeniem ukrywania trudności.',
      transcript: 'Brzmi niemal zbyt prosto. Gdzie był haczyk?',
    },
    {
      id: 'DBT_03',
      file: 'DBT/DBT_03_konflikt_interesow.mp3',
      category: 'DRILL_SKEPTIC',
      intent: 'Pytanie o tarcia polityczne lub sprzeczne cele w organizacji.',
      transcript: 'A nie pojawił się tam żaden konflikt interesów między działami?',
    },
    {
      id: 'DBT_04',
      file: 'DBT/DBT_04_presja_biznesu.mp3',
      category: 'DRILL_SKEPTIC',
      intent: 'Test odporności na presję interesariuszy biznesowych.',
      transcript: 'Biznes naprawdę zgodził się na to bez żadnego oporu?',
    },
    {
      id: 'DBT_05',
      file: 'DBT/DBT_05_dlug_techniczny.mp3',
      category: 'DRILL_SKEPTIC',
      intent: 'Sprawdzenie długofalowych konsekwencji szybkich poprawek.',
      transcript: 'Nie odbiło się to potem długiem technicznym albo problemami na produkcji?',
    },
    {
      id: 'DBT_06',
      file: 'DBT/DBT_06_skrot_myslowy.mp3',
      category: 'DRILL_SKEPTIC',
      intent: 'Wychwycenie luki logicznej i żądanie precyzyjnego opisu krok po kroku.',
      transcript: 'Poczekaj, chyba zastosowałeś spory skrót myślowy. Wyjaśnij krok po kroku, jak to spiąłeś.',
    },
    {
      id: 'DBT_07',
      file: 'DBT/DBT_07_kto_odpowiadal.mp3',
      category: 'DRILL_SKEPTIC',
      intent: 'Identyfikacja faktycznego właściciela decyzji (accountability).',
      transcript: 'Kto ostatecznie podpisał się pod tą decyzją i wziął za nią odpowiedzialność?',
    },
    {
      id: 'DBT_08',
      file: 'DBT/DBT_08_plan_b.mp3',
      category: 'DRILL_SKEPTIC',
      intent: 'Weryfikacja planu awaryjnego (contingency plan / rollback).',
      transcript: 'A co zrobilibyście, gdyby ten plan całkowicie legł w gruzach w pierwszej godzinie?',
    },
    {
      id: 'DBT_09',
      file: 'DBT/DBT_09_prowizorka.mp3',
      category: 'DRILL_SKEPTIC',
      intent: 'Sprawdzenie czy rozwiązanie stało się trwałym długiem technicznym.',
      transcript: 'Czy to było docelowe rozwiązanie, czy typowa prowizorka, która została na lata?',
    },
    {
      id: 'DBT_10',
      file: 'DBT/DBT_10_weryfikacja_efektu.mp3',
      category: 'DRILL_SKEPTIC',
      intent: 'Sprawdzenie mechanizmu długoterminowej weryfikacji rezultatów.',
      transcript: 'W jaki sposób zweryfikowaliście po miesiącu, że to faktycznie zadziałało?',
    },
    {
      id: 'BAR_01',
      file: 'BAR/BAR_01_sekunda_wejscie.mp3',
      category: 'FLOW_BARGEIN',
      intent: 'Płynne przerwanie zbyt długiej lub niecelnej wypowiedzi.',
      transcript: 'Sekundę, wejdę Ci w słowo...',
    },
    {
      id: 'BAR_02',
      file: 'BAR/BAR_02_zatrzymajmy_sie.mp3',
      category: 'FLOW_BARGEIN',
      intent: 'Wstrzymanie monologu i skupienie na jednym kluczowym zdaniu.',
      transcript: 'Zatrzymajmy się na chwilę przy tym jednym zdaniu.',
    },
    {
      id: 'BAR_03',
      file: 'BAR/BAR_03_doprecyzujmy.mp3',
      category: 'FLOW_BARGEIN',
      intent: 'Uprzejme wtrącenie w celu natychmiastowego wyjaśnienia nieścisłości.',
      transcript: 'Wybacz, że przerwę, ale doprecyzujmy jedną kluczową rzecz.',
    },
    {
      id: 'BAR_04',
      file: 'BAR/BAR_04_zanim_dalej.mp3',
      category: 'FLOW_BARGEIN',
      intent: 'Zatrzymanie narracji przed kolejnym etapem w celu poznania kalkulacji.',
      transcript: 'Zanim przejdziesz dalej – jak to dokładnie policzyliście?',
    },
    {
      id: 'BAR_05',
      file: 'BAR/BAR_05_wrocmy_do_poczatku.mp3',
      category: 'FLOW_BARGEIN',
      intent: 'Cofnięcie rozmowy do punktu wyjścia.',
      transcript: 'Cofnijmy się o jeden krok, bo to jest najważniejszy punkt.',
    },
    {
      id: 'BAR_06',
      file: 'BAR/BAR_06_czekaj_czekaj.mp3',
      category: 'FLOW_BARGEIN',
      intent: 'Ekspresyjne zatrzymanie przy wykryciu rażącej anomalii procesowej.',
      transcript: 'Czekaj, czekaj... czy dobrze rozumiem, że zrobiliście to ręcznie?',
    },
    {
      id: 'BAR_07',
      file: 'BAR/BAR_07_wytnijmy_wstep.mp3',
      category: 'FLOW_BARGEIN',
      intent: 'Ucięcie zbędnego tła i przejście od razu do sedna awarii.',
      transcript: 'Pomińmy tło organizacyjne, przejdźmy od razu do samej awarii.',
    },
    {
      id: 'BAR_08',
      file: 'BAR/BAR_08_nie_uciekajmy.mp3',
      category: 'FLOW_BARGEIN',
      intent: 'Zablokowanie ucieczki w teorię i skupienie na realnej decyzji.',
      transcript: 'Nie uciekajmy w teorię, zostańmy przy Twojej decyzji z tamtego dnia.',
    },
    {
      id: 'BAR_09',
      file: 'BAR/BAR_09_jedna_uwaga.mp3',
      category: 'FLOW_BARGEIN',
      intent: 'Krótka dygresja rekrutera przed kontynuacją.',
      transcript: 'Jedna krótka dygresja z mojej strony, zanim dokończysz...',
    },
    {
      id: 'BAR_10',
      file: 'BAR/BAR_10_lapie_o_co_chodzi.mp3',
      category: 'FLOW_BARGEIN',
      intent: 'Zasygnalizowanie, że kontekst jest jasny i prośba o podanie finału.',
      transcript: 'Łapię ogólny zarys, powiedz mi tylko o samym finale.',
    },
    {
      id: 'ERR_01',
      file: 'ERR/ERR_01_ucielo_koncowke.mp3',
      category: 'FLOW_ERROR',
      intent: 'Obsługa uciętego audio pod koniec wypowiedzi.',
      transcript: 'Przepraszam, ucięło Ci końcówkę zdania. Możesz powtórzyć ostatnią myśl?',
    },
    {
      id: 'ERR_02',
      file: 'ERR/ERR_02_przerywa_polaczenie.mp3',
      category: 'FLOW_ERROR',
      intent: 'Reakcja na rwane pakiety audio / jitter sieciowy.',
      transcript: 'Coś lekko przerywa na łączu. Powtórzysz dwa ostatnie zdania?',
    },
    {
      id: 'ERR_03',
      file: 'ERR/ERR_03_nie_doslyszalem.mp3',
      category: 'FLOW_ERROR',
      intent: 'Prośba o powtórzenie pojedynczego niezrozumiałego słowa.',
      transcript: 'Nie dosłyszałem jednego słowa – co dokładnie tam padło?',
    },
    {
      id: 'ERR_04',
      file: 'ERR/ERR_04_zaklocenia_mikrofonu.mp3',
      category: 'FLOW_ERROR',
      intent: 'Zgłoszenie chwilowego przesteru lub szumu mikrofonu.',
      transcript: 'Mamy małe zakłócenia na mikrofonie, ale mów dalej, już powinno być w porządku.',
    },
    {
      id: 'ERR_05',
      file: 'ERR/ERR_05_chwilowy_lag.mp3',
      category: 'FLOW_ERROR',
      intent: 'Zamaskowanie opóźnienia sieciowego i prośba o podsumowanie.',
      transcript: 'Mieliśmy chwilowy lag. Czy mógłbyś jeszcze raz podsumować ten wniosek?',
    },
    {
      id: 'ERR_06',
      file: 'ERR/ERR_06_glosniej_prosze.mp3',
      category: 'FLOW_ERROR',
      intent: 'Wskazówka dotycząca zbyt cichego sygnału audio użytkownika.',
      transcript: 'Mógłbyś mówić odrobinę głośniej? Teraz jest nieco lepiej.',
    },
    {
      id: 'ERR_07',
      file: 'ERR/ERR_07_brak_dzwieku.mp3',
      category: 'FLOW_ERROR',
      intent: 'Reakcja na wykrycie dłuższej luki w przesyle dźwięku.',
      transcript: 'Przez trzy sekundy nic nie było słychać. O czym mówiłeś przed chwilą?',
    },
    {
      id: 'ERR_08',
      file: 'ERR/ERR_08_rozlaczylo_nas.mp3',
      category: 'FLOW_ERROR',
      intent: 'Powrót do rozmowy po zresetowaniu połączenia.',
      transcript: 'Chyba na moment zerwało połączenie. Kontynuuj od momentu decyzji.',
    },
    {
      id: 'ERR_09',
      file: 'ERR/ERR_09_szum_w_tle.mp3',
      category: 'FLOW_ERROR',
      intent: 'Odnotowanie zakłóceń otoczenia bez przerywania sesji.',
      transcript: 'Wkradł się jakiś szum, ale już Cię słyszę. Dokończ, proszę.',
    },
    {
      id: 'ERR_10',
      file: 'ERR/ERR_10_pauza_techniczna.mp3',
      category: 'FLOW_ERROR',
      intent: 'Potwierdzenie stabilizacji łącza po problemach technicznych.',
      transcript: 'Dobra, wygląda na to, że łącze jest stabilne. Możemy wracać do tematu.',
    },
    {
      id: 'TIM_01',
      file: 'TIM/TIM_01_zegar_goni.mp3',
      category: 'FLOW_TIMING',
      intent: 'Wymuszenie dwuzdaniowego podsumowania ze względu na czas.',
      transcript: 'Czas nas trochę goni, więc podsumujmy ten wątek w dwóch zdaniach.',
    },
    {
      id: 'TIM_02',
      file: 'TIM/TIM_02_ostatnie_pytanie.mp3',
      category: 'FLOW_TIMING',
      intent: 'Zapowiedź ostatniego pytania merytorycznego w wywiadzie.',
      transcript: 'Mamy czas na jeszcze jedno, ostatnie pytanie techniczne.',
    },
    {
      id: 'TIM_03',
      file: 'TIM/TIM_03_polmetek.mp3',
      category: 'FLOW_TIMING',
      intent: 'Sygnał kontrolny w połowie wyznaczonego czasu spotkania.',
      transcript: 'Jesteśmy dokładnie w połowie zaplanowanego czasu rozmowy.',
    },
    {
      id: 'TIM_04',
      file: 'TIM/TIM_04_krotka_pilka.mp3',
      category: 'FLOW_TIMING',
      intent: 'Prośba o szybką, jednoznaczną odpowiedź bez rozwlekłego wstępu.',
      transcript: 'Krótka piłka z mojej strony, bo uciekają nam minuty.',
    },
    {
      id: 'TIM_05',
      file: 'TIM/TIM_05_przyspieszmy.mp3',
      category: 'FLOW_TIMING',
      intent: 'Zwiększenie tempa wywiadu w celu pokrycia całej agendy.',
      transcript: 'Przyspieszmy odrobinę, żebyśmy zdążyli przejść przez wszystkie bloki tematyczne.',
    },
    {
      id: 'TIM_06',
      file: 'TIM/TIM_06_dwie_minuty.mp3',
      category: 'FLOW_TIMING',
      intent: 'Ostrzeżenie o ostatnich 120 sekundach danej sekcji.',
      transcript: 'Zostały nam ostatnie dwie minuty na tę część.',
    },
    {
      id: 'TIM_07',
      file: 'TIM/TIM_07_zamykamy_blok.mp3',
      category: 'FLOW_TIMING',
      intent: 'Przejście do nowej sekcji z powodu upływu okna czasowego.',
      transcript: 'Zamykamy ten blok pytań i przechodzimy do kolejnej kategorii.',
    },
    {
      id: 'TIM_08',
      file: 'TIM/TIM_08_punktualnosc.mp3',
      category: 'FLOW_TIMING',
      intent: 'Płynne sterowanie zakończeniem w celu dotrzymania slotu w kalendarzu.',
      transcript: 'Chciałbym uszanować Twój czas, więc płynnie przejdźmy do finału.',
    },
    {
      id: 'TIM_09',
      file: 'TIM/TIM_09_sprawny_odstep.mp3',
      category: 'FLOW_TIMING',
      intent: 'Pozytywny feedback o dobrym tempie rozmowy i zapasie czasu.',
      transcript: 'Okej, sprawnie nam to idzie, mamy jeszcze chwilę zapasu.',
    },
    {
      id: 'TIM_10',
      file: 'TIM/TIM_10_ostatnia_prosta.mp3',
      category: 'FLOW_TIMING',
      intent: 'Sygnał wejścia w ostatnią fazę wywiadu.',
      transcript: 'Jesteśmy na ostatniej prostej wywiadu.',
    },
    {
      id: 'END_01',
      file: 'END/END_01_dzieki_za_odpowiedzi.mp3',
      category: 'FLOW_CLOSING',
      intent: 'Podziękowanie za wyczerpujące odpowiedzi merytoryczne.',
      transcript: 'Świetnie, dzięki za wyczerpujące odpowiedzi na wszystkie pytania.',
    },
    {
      id: 'END_02',
      file: 'END/END_02_koniec_czesci_technicznej.mp3',
      category: 'FLOW_CLOSING',
      intent: 'Formalne zamknięcie etapu pytań sprawdzających wiedzę.',
      transcript: 'To zamyka naszą część techniczną. Z mojej strony to wszystko.',
    },
    {
      id: 'END_03',
      file: 'END/END_03_pytania_od_kandydata.mp3',
      category: 'FLOW_CLOSING',
      intent: 'Oddanie głosu kandydatowi na pytania o firmę/projekt.',
      transcript: 'Czy masz na koniec jakieś pytania do mnie albo odnośnie samego projektu?',
    },
    {
      id: 'END_04',
      file: 'END/END_04_kolejne_kroki.mp3',
      category: 'FLOW_CLOSING',
      intent: 'Informacja o trybie przekazania decyzji rekrutacyjnej.',
      transcript: 'Dalsze informacje o kolejnych krokach rekrutacji przekażemy drogą mailową.',
    },
    {
      id: 'END_05',
      file: 'END/END_05_mila_rozmowa.mp3',
      category: 'FLOW_CLOSING',
      intent: 'Kulturalne podziękowanie za merytoryczne spotkanie.',
      transcript: 'Dziękuję za Twój czas i bardzo konkretną, merytoryczną rozmowę.',
    },
    {
      id: 'END_06',
      file: 'END/END_06_zapisane_notatki.mp3',
      category: 'FLOW_CLOSING',
      intent: 'Potwierdzenie zapisu danych i zapowiedź kontaktu.',
      transcript: 'Mam zanotowane wszystkie kluczowe punkty. Będziemy w kontakcie.',
    },
    {
      id: 'END_07',
      file: 'END/END_07_do_uslyszenia.mp3',
      category: 'FLOW_CLOSING',
      intent: 'Krótkie pożegnanie zamykające.',
      transcript: 'Dzięki za spotkanie i do usłyszenia wkrótce. Cześć!',
    },
    {
      id: 'END_08',
      file: 'END/END_08_udany_dzien.mp3',
      category: 'FLOW_CLOSING',
      intent: 'Życzenie powodzenia w dalszym procesie rekrutacyjnym.',
      transcript: 'Życzę udanego dnia i powodzenia w kolejnych etapach.',
    },
    {
      id: 'END_09',
      file: 'END/END_09_zamykamy_sesje.mp3',
      category: 'FLOW_CLOSING',
      intent: 'Instrukcja technicznego zakończenia i rozłączenia sesji.',
      transcript: 'Zamykamy naszą sesję. Możesz się spokojnie rozłączyć.',
    },
    {
      id: 'END_10',
      file: 'END/END_10_dobra_robota.mp3',
      category: 'FLOW_CLOSING',
      intent: 'Nieformalne, pozytywne podsumowanie przejścia przez materiał.',
      transcript: 'Dobra robota, przeszliśmy przez cały zaplanowany materiał. Trzymaj się!',
    },
  ],
};

/** Indeks po ID dla dostępu w czasie O(1) */
export const AUDIO_ITEMS_BY_ID: ReadonlyMap<string, AudioManifestItem> = new Map(
  RECRUITER_AUDIO_MANIFEST.items.map((item) => [item.id, item])
);

/** Zgrupowane nagrania per kategoria */
export const AUDIO_ITEMS_BY_CATEGORY: ReadonlyMap<string, AudioManifestItem[]> = (() => {
  const map = new Map<string, AudioManifestItem[]>();
  for (const item of RECRUITER_AUDIO_MANIFEST.items) {
    const list = map.get(item.category) || [];
    list.push(item);
    map.set(item.category, list);
  }
  return map;
})();
