import { OccupationalProfessionEntry } from './types';

export const INITIAL_OCCUPATIONAL_DATA: OccupationalProfessionEntry[] = [
  {
    id: 'kominiarz',
    profesja: 'Kominiarz / Mistrz Kominiarski',
    branza: 'Usługi Kominiarskie & Bezpieczeństwo Pożarowe',
    slowosiec_sense_id: 'd5225952-aac4-11ed-aae5-0242ac130002',
    slowosiec_data: {
      lemma: 'kominiarz',
      synset_id: 'plwordnet_kominiarz_1',
      hiperonimy: [
        { lemma: 'rzemieślnik', sense_id: 'rzemieslnik-1' },
        { lemma: 'specjalista', sense_id: 'specjalista-1' },
      ],
    },
    osoby: ['kominiarz', 'kominiarka', 'mistrz kominiarski', 'czeladnik kominiarski'],
    obiekty: ['komin', 'wentylacja', 'przewód kominowy', 'przewód dymowy', 'przewód spalinowy', 'piec', 'kocioł gazowy', 'klapa dymowa'],
    czynnosci: ['czyszczenie', 'czyści', 'udrożnianie', 'przegląd', 'kontrola techniczna', 'inspekcja', 'pomiary ciągu', 'odbiór kominiarski'],
    narzedzia: ['szczotka kominiarska', 'kula kominiarska', 'kamera inspekcyjna', 'anemometr cyfrowy', 'linogryz', 'wycior'],
    miejsce: ['dach', 'kotłownia', 'poddasze', 'budynek mieszkalny', 'obiekt przemysłowy'],
  },
  {
    id: 'piekarz',
    profesja: 'Piekarz / Mistrz Piekarski',
    branza: 'Przetwórstwo Spożywcze & Piekarnictwo',
    slowosiec_sense_id: 'e6336a63-aac4-11ed-aae5-0242ac130003',
    slowosiec_data: {
      lemma: 'piekarz',
      synset_id: 'plwordnet_piekarz_1',
      hiperonimy: [
        { lemma: 'rzemieślnik', sense_id: 'rzemieslnik-1' },
        { lemma: 'wytwórca', sense_id: 'wytworca-1' },
      ],
    },
    osoby: ['piekarz', 'mistrz piekarski', 'pomocnik piekarza'],
    obiekty: ['chleb', 'bułka', 'mąka', 'zakwas piekarski', 'ciasto chlebowe', 'drożdże', 'wyroby cukiernicze'],
    czynnosci: ['pieczenie', 'mieszenie', 'wyrabianie ciasta', 'formowanie bochenków', 'fermentacja', 'wypiek', 'kontrola temperatury'],
    narzedzia: ['piec piekarniczy', 'piec wsadowy', 'mieszałka spiralna', 'dzielarka ciasta', 'łopata piekarska', 'garownik'],
    miejsce: ['piekarnia', 'zakład piekarniczy', 'manufaktura chleba'],
  },
  {
    id: 'stolarz',
    profesja: 'Stolarz Meblowy / Cieśla',
    branza: 'Obróbka Drewna & Meblarstwo',
    slowosiec_sense_id: 'f7447b74-aac4-11ed-aae5-0242ac130004',
    slowosiec_data: {
      lemma: 'stolarz',
      synset_id: 'plwordnet_stolarz_1',
      hiperonimy: [
        { lemma: 'rzemieślnik', sense_id: 'rzemieslnik-1' },
      ],
    },
    osoby: ['stolarz', 'cieśla', 'pomocnik stolarza', 'montażysta mebli'],
    obiekty: ['drewno lite', 'płyta meblowa MDF', 'fornir', 'meble kuchenne', 'schody drewniane', 'okucia meblowe Blum', 'blaty'],
    czynnosci: ['cięcie', 'frezowanie', 'szlifowanie', 'klejenie', 'montaż mebli', 'trasowanie', 'olejowanie', 'lakierowanie'],
    narzedzia: ['pilarka formatowa', 'frezarka górnowrzecionowa', 'szlifierka mimośrodowa', 'okleiniarka krawędzi', 'wkrętarka', 'ścisk stolarski'],
    miejsce: ['warsztat stolarski', 'stolarnia', 'obiekt klienta'],
  },
  {
    id: 'monter_hvac',
    profesja: 'Monter & Serwisant Instalacji HVAC / Kotłów Gazowych',
    branza: 'Instalacje, Gazownictwo & HVAC',
    slowosiec_sense_id: 'a1111111-aac4-11ed-aae5-0242ac130005',
    slowosiec_data: {
      lemma: 'monter',
      hiperonimy: [{ lemma: 'technik' }, { lemma: 'instalator' }],
    },
    osoby: ['monter', 'instalator', 'serwisant', 'hydraulik', 'technik hvac'],
    obiekty: ['kocioł gazowy', 'pompa ciepła', 'klimatyzator split', 'instalacja sanitarna', 'rurociąg miedziany', 'rura pex', 'wymiennik ciepła'],
    czynnosci: ['montaż', 'instalacja', 'próba szczelności', 'analiza spalin', 'serwis', 'odpowietrzanie', 'zgrzewanie', 'lutowanie'],
    narzedzia: ['analizator spalin testo', 'detektor gazu', 'pompa próżniowa', 'zgrzewarka elektrooporowa', 'kielicharka', 'manometr'],
    miejsce: ['kotłownia', 'budynek mieszkalny', 'hala przemysłowa', 'maszynownia'],
  },
  {
    id: 'spawacz',
    profesja: 'Spawacz TIG / MAG / Ślusarz',
    branza: 'Spawalnictwo & Obróbka Metali',
    slowosiec_sense_id: 'b2222222-aac4-11ed-aae5-0242ac130006',
    slowosiec_data: {
      lemma: 'spawacz',
      hiperonimy: [{ lemma: 'rzemieślnik' }, { lemma: 'metalowiec' }],
    },
    osoby: ['spawacz', 'ślusarz', 'spawacz tig', 'spawacz mag'],
    obiekty: ['konstrukcja stalowa', 'rurociąg ciśnieniowy', 'stal nierdzewna', 'spoina doczołowa', 'spoina pachwinowa', 'profile hutnicze'],
    czynnosci: ['spawanie tig 141', 'spawanie mag 135', 'trasowanie', 'ukosowanie krawędzi', 'badania wizualne vt2', 'sczepianie elementów'],
    narzedzia: ['spawarka fronius', 'spawarka kemppi', 'przyłbica spawalnicza', 'szlifierka kątowa', 'spoinomierz', 'ukosowarka'],
    miejsce: ['warsztat spawalniczy', 'stocznia', 'budowa przemysłowa', 'hala produkcyjna'],
  },
  {
    id: 'elektryk',
    profesja: 'Elektryk / Elektromonter / Automatyk (SEP G1)',
    branza: 'Elektryka & Automatyka Przemysłowa',
    slowosiec_sense_id: 'c3333333-aac4-11ed-aae5-0242ac130007',
    slowosiec_data: {
      lemma: 'elektryk',
      hiperonimy: [{ lemma: 'elektromonter' }, { lemma: 'specjalista' }],
    },
    osoby: ['elektryk', 'elektromonter', 'automatyk', 'pomiarowiec'],
    obiekty: ['rozdzielnica elektryczna nn', 'trasa kablowa', 'sterownik plc', 'wyłącznik rcd', 'układ zasilania', 'silnik elektryczny'],
    czynnosci: ['pomiary elektryczne', 'prefabrykacja szaf', 'sznurowanie', 'usuwanie awarii', 'programowanie plc', 'podłączanie instalacji'],
    narzedzia: ['miernik sonel', 'multimetr fluke', 'zaciskarka tulejek', 'ściągacz izolacji jokari', 'kamera termowizyjna'],
    miejsce: ['stacja transformatorowa', 'rozdzielnia', 'linia produkcyjna', 'budynek biurowy'],
  },
  {
    id: 'magazynier',
    profesja: 'Magazynier / Operator Wózka Widłowego UDT / WMS',
    branza: 'Logistyka Magazynowa & E-Commerce',
    slowosiec_sense_id: 'd4444444-aac4-11ed-aae5-0242ac130008',
    slowosiec_data: {
      lemma: 'magazynier',
      hiperonimy: [{ lemma: 'logistyk' }],
    },
    osoby: ['magazynier', 'operator wózka widłowego', 'picker', 'kompletator'],
    obiekty: ['paleta euro', 'regał wysokiego składowania', 'przesyłka kurierska', 'etykieta gs1', 'towar handlowy', 'naczepa tir'],
    czynnosci: ['kompletacja zamówień', 'obsługa wózka widłowego', 'rozładunek naczepy', 'przyjęcia towaru', 'inwentaryzacja', 'skanowanie wms'],
    narzedzia: ['wózek widłowy linde', 'wózek reach truck', 'terminal skaner zebra', 'owijarka do palet', 'system sap wms'],
    miejsce: ['magazyn wysokiego składu', 'centrum dystrybucyjne', 'hala logistyczna'],
  },
  {
    id: 'kierowca_ce',
    profesja: 'Kierowca Ciężarówki Kat. C+E / Spedytor',
    branza: 'Transport Ciężarowy & Spedycja',
    slowosiec_sense_id: 'e5555555-aac4-11ed-aae5-0242ac130009',
    slowosiec_data: {
      lemma: 'kierowca',
      hiperonimy: [{ lemma: 'przewoźnik' }],
    },
    osoby: ['kierowca', 'kierowca c+e', 'kierowca zawodowy', 'spedytor'],
    obiekty: ['ciągnik siodłowy', 'naczepa firanka', 'ładunek ftl/ltl', 'list przewozowy cmr', 'tachograf cyfrowy', 'towary adr'],
    czynnosci: ['prowadzenie pojazdu', 'zabezpieczanie ładunku pasami', 'kontrola czasu jazdy', 'odprawa celna', 'rozładunek'],
    narzedzia: ['karta kierowcy', 'pasy transportowe ergo', 'maty antypoślizgowe', 'nawigacja gps truck', 'tachograf vdo'],
    miejsce: ['drogi międzynarodowe', 'terminal przeładunkowy', 'parking dla ciężarówek', 'strefa celna'],
  },
  {
    id: 'mechanik_samochodowy',
    profesja: 'Mechanik Samochodowy / Diagnosta KTS',
    branza: 'Motoryzacja & Diagnostyka Pojazdowa',
    slowosiec_sense_id: 'f6666666-aac4-11ed-aae5-0242ac130010',
    slowosiec_data: {
      lemma: 'mechanik',
      hiperonimy: [{ lemma: 'serwisant' }],
    },
    osoby: ['mechanik', 'diagnosta', 'elektromechanik', 'wulkanizator'],
    obiekty: ['silnik spalinowy', 'układ rozrządu', 'magistrala can', 'zawieszenie', 'tarcze i klocki hamulcowe', 'wtryskiwacz common rail'],
    czynnosci: ['diagnostyka komputerowa', 'wymiana rozrządu', 'naprawa zawieszenia', 'ustawianie geometrii 3d', 'kasowanie błędów ecu'],
    narzedzia: ['tester bosch kts', 'oscyloskop picoscope', 'urządzenie hunter 3d', 'klucz dynamometryczny', 'podnośnik kolumnowy'],
    miejsce: ['warsztat samochodowy', 'stacja kontroli pojazdów', 'serwis aso'],
  },
  {
    id: 'ksiegowa',
    profesja: 'Księgowa / Specjalista ds. Finansów i Kadr',
    branza: 'Finanse, Rachunkowość & Podatki',
    slowosiec_sense_id: '17777777-aac4-11ed-aae5-0242ac130011',
    slowosiec_data: {
      lemma: 'księgowa',
      hiperonimy: [{ lemma: 'finansista' }, { lemma: 'ekonomista' }],
    },
    osoby: ['księgowa', 'księgowy', 'kadrowa', 'doradca podatkowy', 'audytor'],
    obiekty: ['faktura vat', 'deklaracja vat-7', 'deklaracja cit-8', 'plik jpk_v7', 'bilans finansowy', 'lista płac', 'deklaracja zus dra'],
    czynnosci: ['księgowanie', 'dekretacja dokumentów', 'sporządzanie deklaracji podatkowych', 'rozliczanie płac', 'zamykanie roku obrotowego'],
    narzedzia: ['comarch erp optima', 'symfonia', 'program płatnik zus', 'arkusz excel', 'system ksef'],
    miejsce: ['biuro rachunkowe', 'dział finansowy', 'kancelaria podatkowa'],
  },
  {
    id: 'programista_software',
    profesja: 'Programista / Software Engineer (Fullstack/Backend/Frontend)',
    branza: 'IT & Inżynieria Oprogramowania',
    slowosiec_sense_id: '28888888-aac4-11ed-aae5-0242ac130012',
    slowosiec_data: {
      lemma: 'programista',
      hiperonimy: [{ lemma: 'inżynier' }, { lemma: 'informatyk' }],
    },
    osoby: ['programista', 'developer', 'software engineer', 'architekt it'],
    obiekty: ['aplikacja webowa', 'api rest', 'baza danych postgresql', 'mikroserwis', 'komponent react', 'kod źródłowy'],
    czynnosci: ['programowanie', 'projektowanie architektury', 'implementacja endpointów', 'refaktoryzacja', 'code review', 'wdrażanie'],
    narzedzia: ['typescript', 'react', 'node.js', 'docker', 'git', 'vs code', 'postgresql'],
    miejsce: ['biuro it', 'praca zdalna (remote)', 'serwerownia'],
  },
];
