import { PolishLocality } from './types';

/**
 * Rejestr polskich miast, stolic województw, miast na prawach powiatu,
 * stolic powiatów i ośrodków subregionalnych z precyzyjnymi współrzędnymi GPS WGS-84.
 */
export const POLISH_LOCALITIES: PolishLocality[] = [
  // --- Metropolie i Miasta Wojewódzkie ---
  {
    id: 'warszawa',
    name: 'Warszawa',
    voivodeship: 'mazowieckie',
    powiat: 'm. Warszawa',
    lat: 52.2297,
    lng: 21.0122,
    isVoivodeshipCapital: true,
    isCountyCity: true,
    urbanAreaId: 'warszawa_metro',
    aliases: ['wwa', 'warsaw', 'stolica'],
  },
  {
    id: 'krakow',
    name: 'Kraków',
    voivodeship: 'małopolskie',
    powiat: 'm. Kraków',
    lat: 50.0647,
    lng: 19.945,
    isVoivodeshipCapital: true,
    isCountyCity: true,
    urbanAreaId: 'krakow_metro',
    aliases: ['krk', 'cracow', 'krakau'],
  },
  {
    id: 'lodz',
    name: 'Łódź',
    voivodeship: 'łódzkie',
    powiat: 'm. Łódź',
    lat: 51.7592,
    lng: 19.456,
    isVoivodeshipCapital: true,
    isCountyCity: true,
    urbanAreaId: 'lodz_metro',
    aliases: ['ldz'],
  },
  {
    id: 'wroclaw',
    name: 'Wrocław',
    voivodeship: 'dolnośląskie',
    powiat: 'm. Wrocław',
    lat: 51.1079,
    lng: 17.0385,
    isVoivodeshipCapital: true,
    isCountyCity: true,
    urbanAreaId: 'wroclaw_metro',
    aliases: ['wroc', 'breslau'],
  },
  {
    id: 'poznan',
    name: 'Poznań',
    voivodeship: 'wielkopolskie',
    powiat: 'm. Poznań',
    lat: 52.4064,
    lng: 16.9252,
    isVoivodeshipCapital: true,
    isCountyCity: true,
    urbanAreaId: 'poznan_metro',
    aliases: ['pozn', 'posen'],
  },
  {
    id: 'gdansk',
    name: 'Gdańsk',
    voivodeship: 'pomorskie',
    powiat: 'm. Gdańsk',
    lat: 54.352,
    lng: 18.6466,
    isVoivodeshipCapital: true,
    isCountyCity: true,
    urbanAreaId: 'trojmiasto',
    aliases: ['gdn', 'danzig', '3city', 'trojmiasto'],
  },
  {
    id: 'szczecin',
    name: 'Szczecin',
    voivodeship: 'zachodniopomorskie',
    powiat: 'm. Szczecin',
    lat: 53.4285,
    lng: 14.5528,
    isVoivodeshipCapital: true,
    isCountyCity: true,
    urbanAreaId: 'szczecin_metro',
    aliases: ['szcz', 'stettin'],
  },
  {
    id: 'bydgoszcz',
    name: 'Bydgoszcz',
    voivodeship: 'kujawsko-pomorskie',
    powiat: 'm. Bydgoszcz',
    lat: 53.1235,
    lng: 18.0084,
    isVoivodeshipCapital: true,
    isCountyCity: true,
    urbanAreaId: 'bydgoszcz_torun',
    aliases: ['bdg'],
  },
  {
    id: 'lublin',
    name: 'Lublin',
    voivodeship: 'lubelskie',
    powiat: 'm. Lublin',
    lat: 51.2465,
    lng: 22.5684,
    isVoivodeshipCapital: true,
    isCountyCity: true,
    urbanAreaId: 'lublin_metro',
    aliases: ['lbl'],
  },
  {
    id: 'bialystok',
    name: 'Białystok',
    voivodeship: 'podlaskie',
    powiat: 'm. Białystok',
    lat: 53.1325,
    lng: 23.1688,
    isVoivodeshipCapital: true,
    isCountyCity: true,
    urbanAreaId: 'bialystok_metro',
    aliases: ['bstok'],
  },
  {
    id: 'katowice',
    name: 'Katowice',
    voivodeship: 'śląskie',
    powiat: 'm. Katowice',
    lat: 50.2649,
    lng: 19.0238,
    isVoivodeshipCapital: true,
    isCountyCity: true,
    urbanAreaId: 'gop',
    aliases: ['kat', 'kato', 'gop', 'silesia'],
  },
  {
    id: 'gdynia',
    name: 'Gdynia',
    voivodeship: 'pomorskie',
    powiat: 'm. Gdynia',
    lat: 54.5189,
    lng: 18.5305,
    isCountyCity: true,
    urbanAreaId: 'trojmiasto',
    aliases: ['gdy', '3city', 'trojmiasto'],
  },
  {
    id: 'czestochowa',
    name: 'Częstochowa',
    voivodeship: 'śląskie',
    powiat: 'm. Częstochowa',
    lat: 50.8118,
    lng: 19.1203,
    isCountyCity: true,
    aliases: ['czwa', 'czest'],
  },
  {
    id: 'radom',
    name: 'Radom',
    voivodeship: 'mazowieckie',
    powiat: 'm. Radom',
    lat: 51.4027,
    lng: 21.1471,
    isCountyCity: true,
    aliases: ['rdm'],
  },
  {
    id: 'torun',
    name: 'Toruń',
    voivodeship: 'kujawsko-pomorskie',
    powiat: 'm. Toruń',
    lat: 53.0138,
    lng: 18.5984,
    isVoivodeshipCapital: true,
    isCountyCity: true,
    urbanAreaId: 'bydgoszcz_torun',
    aliases: ['trn', 'thorn'],
  },
  {
    id: 'rzeszow',
    name: 'Rzeszów',
    voivodeship: 'podkarpackie',
    powiat: 'm. Rzeszów',
    lat: 50.0412,
    lng: 21.9991,
    isVoivodeshipCapital: true,
    isCountyCity: true,
    urbanAreaId: 'rzeszow_metro',
    aliases: ['rze'],
  },
  {
    id: 'kielce',
    name: 'Kielce',
    voivodeship: 'świętokrzyskie',
    powiat: 'm. Kielce',
    lat: 50.8661,
    lng: 20.6286,
    isVoivodeshipCapital: true,
    isCountyCity: true,
    urbanAreaId: 'kielce_metro',
    aliases: ['klc'],
  },
  {
    id: 'olsztyn',
    name: 'Olsztyn',
    voivodeship: 'warmińsko-mazurskie',
    powiat: 'm. Olsztyn',
    lat: 53.7784,
    lng: 20.4801,
    isVoivodeshipCapital: true,
    isCountyCity: true,
    urbanAreaId: 'olsztyn_metro',
    aliases: ['olsz', 'allenstein'],
  },
  {
    id: 'opole',
    name: 'Opole',
    voivodeship: 'opolskie',
    powiat: 'm. Opole',
    lat: 50.6751,
    lng: 17.9213,
    isVoivodeshipCapital: true,
    isCountyCity: true,
    urbanAreaId: 'opole_metro',
    aliases: ['oppeln'],
  },
  {
    id: 'zielona_gora',
    name: 'Zielona Góra',
    voivodeship: 'lubuskie',
    powiat: 'm. Zielona Góra',
    lat: 51.9356,
    lng: 15.5062,
    isVoivodeshipCapital: true,
    isCountyCity: true,
    aliases: ['zg', 'grunberg'],
  },
  {
    id: 'gorzow_wielkopolski',
    name: 'Gorzów Wielkopolski',
    voivodeship: 'lubuskie',
    powiat: 'm. Gorzów Wielkopolski',
    lat: 52.7368,
    lng: 15.2288,
    isVoivodeshipCapital: true,
    isCountyCity: true,
    aliases: ['gorzow', 'landsberg'],
  },

  // --- Małopolska & Podkarpacie (w tym Tarnów, Nowy Sącz, Rzeszów) ---
  {
    id: 'tarnow',
    name: 'Tarnów',
    voivodeship: 'małopolskie',
    powiat: 'm. Tarnów',
    lat: 50.0121,
    lng: 20.9858,
    isCountyCity: true,
    aliases: ['tar'],
  },
  {
    id: 'nowy_sacz',
    name: 'Nowy Sącz',
    voivodeship: 'małopolskie',
    powiat: 'm. Nowy Sącz',
    lat: 49.625,
    lng: 20.6975,
    isCountyCity: true,
  },
  {
    id: 'oswiecim',
    name: 'Oświęcim',
    voivodeship: 'małopolskie',
    powiat: 'oświęcimski',
    lat: 50.0344,
    lng: 19.2393,
  },
  {
    id: 'chrzanow',
    name: 'Chrzanów',
    voivodeship: 'małopolskie',
    powiat: 'chrzanowski',
    lat: 50.1372,
    lng: 19.4022,
  },
  {
    id: 'olkusz',
    name: 'Olkusz',
    voivodeship: 'małopolskie',
    powiat: 'olkuski',
    lat: 50.28,
    lng: 19.5628,
  },
  {
    id: 'nowy_targ',
    name: 'Nowy Targ',
    voivodeship: 'małopolskie',
    powiat: 'nowotarski',
    lat: 49.4778,
    lng: 20.0325,
  },
  {
    id: 'bochnia',
    name: 'Bochnia',
    voivodeship: 'małopolskie',
    powiat: 'bocheński',
    lat: 49.9689,
    lng: 20.4303,
  },
  {
    id: 'wieliczka',
    name: 'Wieliczka',
    voivodeship: 'małopolskie',
    powiat: 'wielicki',
    lat: 49.9872,
    lng: 20.0647,
    urbanAreaId: 'krakow_metro',
  },
  {
    id: 'zakopane',
    name: 'Zakopane',
    voivodeship: 'małopolskie',
    powiat: 'tatrzański',
    lat: 49.2992,
    lng: 19.9496,
  },
  {
    id: 'krosno',
    name: 'Krosno',
    voivodeship: 'podkarpackie',
    powiat: 'm. Krosno',
    lat: 49.6887,
    lng: 21.7706,
    isCountyCity: true,
  },
  {
    id: 'przemysl',
    name: 'Przemyśl',
    voivodeship: 'podkarpackie',
    powiat: 'm. Przemyśl',
    lat: 49.7839,
    lng: 22.7678,
    isCountyCity: true,
  },
  {
    id: 'tarnobrzeg',
    name: 'Tarnobrzeg',
    voivodeship: 'podkarpackie',
    powiat: 'm. Tarnobrzeg',
    lat: 50.5739,
    lng: 21.6797,
    isCountyCity: true,
  },
  {
    id: 'mielec',
    name: 'Mielec',
    voivodeship: 'podkarpackie',
    powiat: 'mielecki',
    lat: 50.2872,
    lng: 21.4244,
  },
  {
    id: 'stalowa_wola',
    name: 'Stalowa Wola',
    voivodeship: 'podkarpackie',
    powiat: 'stalowowolski',
    lat: 50.5828,
    lng: 22.0536,
  },
  {
    id: 'debica',
    name: 'Dębica',
    voivodeship: 'podkarpackie',
    powiat: 'dębicki',
    lat: 50.0515,
    lng: 21.4114,
  },

  // --- Górnośląsko-Zagłębiowska Metropolia (GOP / Śląsk) ---
  {
    id: 'chorzow',
    name: 'Chorzów',
    voivodeship: 'śląskie',
    powiat: 'm. Chorzów',
    lat: 50.2975,
    lng: 18.9546,
    isCountyCity: true,
    urbanAreaId: 'gop',
    aliases: ['koenigshuette'],
  },
  {
    id: 'gliwice',
    name: 'Gliwice',
    voivodeship: 'śląskie',
    powiat: 'm. Gliwice',
    lat: 50.2945,
    lng: 18.6714,
    isCountyCity: true,
    urbanAreaId: 'gop',
    aliases: ['gleiwitz'],
  },
  {
    id: 'sosnowiec',
    name: 'Sosnowiec',
    voivodeship: 'śląskie',
    powiat: 'm. Sosnowiec',
    lat: 50.2863,
    lng: 19.1041,
    isCountyCity: true,
    urbanAreaId: 'gop',
    aliases: ['sosn'],
  },
  {
    id: 'zabrze',
    name: 'Zabrze',
    voivodeship: 'śląskie',
    powiat: 'm. Zabrze',
    lat: 50.3249,
    lng: 18.7857,
    isCountyCity: true,
    urbanAreaId: 'gop',
    aliases: ['hindenburg'],
  },
  {
    id: 'bytom',
    name: 'Bytom',
    voivodeship: 'śląskie',
    powiat: 'm. Bytom',
    lat: 50.348,
    lng: 18.9328,
    isCountyCity: true,
    urbanAreaId: 'gop',
    aliases: ['beuthen'],
  },
  {
    id: 'bielsko_biala',
    name: 'Bielsko-Biała',
    voivodeship: 'śląskie',
    powiat: 'm. Bielsko-Biała',
    lat: 49.8225,
    lng: 19.0444,
    isCountyCity: true,
    aliases: ['bb'],
  },
  {
    id: 'ruda_slaska',
    name: 'Ruda Śląska',
    voivodeship: 'śląskie',
    powiat: 'm. Ruda Śląska',
    lat: 50.2586,
    lng: 18.8553,
    isCountyCity: true,
    urbanAreaId: 'gop',
  },
  {
    id: 'rybnik',
    name: 'Rybnik',
    voivodeship: 'śląskie',
    powiat: 'm. Rybnik',
    lat: 50.0971,
    lng: 18.5418,
    isCountyCity: true,
  },
  {
    id: 'tychy',
    name: 'Tychy',
    voivodeship: 'śląskie',
    powiat: 'm. Tychy',
    lat: 50.1261,
    lng: 18.9918,
    isCountyCity: true,
    urbanAreaId: 'gop',
  },
  {
    id: 'dabrowa_gornicza',
    name: 'Dąbrowa Górnicza',
    voivodeship: 'śląskie',
    powiat: 'm. Dąbrowa Górnicza',
    lat: 50.3193,
    lng: 19.1914,
    isCountyCity: true,
    urbanAreaId: 'gop',
    aliases: ['dg'],
  },
  {
    id: 'jaworzno',
    name: 'Jaworzno',
    voivodeship: 'śląskie',
    powiat: 'm. Jaworzno',
    lat: 50.2052,
    lng: 19.2747,
    isCountyCity: true,
    urbanAreaId: 'gop',
  },
  {
    id: 'jastrzebie_zdroj',
    name: 'Jastrzębie-Zdrój',
    voivodeship: 'śląskie',
    powiat: 'm. Jastrzębie-Zdrój',
    lat: 49.9542,
    lng: 18.5833,
    isCountyCity: true,
  },
  {
    id: 'myslowice',
    name: 'Mysłowice',
    voivodeship: 'śląskie',
    powiat: 'm. Mysłowice',
    lat: 50.2413,
    lng: 19.1417,
    isCountyCity: true,
    urbanAreaId: 'gop',
  },
  {
    id: 'siemianowice_slaskie',
    name: 'Siemianowice Śląskie',
    voivodeship: 'śląskie',
    powiat: 'm. Siemianowice Śląskie',
    lat: 50.3,
    lng: 19.0333,
    isCountyCity: true,
    urbanAreaId: 'gop',
  },
  {
    id: 'tarnowskie_gory',
    name: 'Tarnowskie Góry',
    voivodeship: 'śląskie',
    powiat: 'tarnogórski',
    lat: 50.4447,
    lng: 18.8569,
    urbanAreaId: 'gop',
    aliases: ['tg'],
  },
  {
    id: 'piekary_slaskie',
    name: 'Piekary Śląskie',
    voivodeship: 'śląskie',
    powiat: 'm. Piekary Śląskie',
    lat: 50.3703,
    lng: 18.9481,
    isCountyCity: true,
    urbanAreaId: 'gop',
  },
  {
    id: 'swietochlowice',
    name: 'Świętochłowice',
    voivodeship: 'śląskie',
    powiat: 'm. Świętochłowice',
    lat: 50.2925,
    lng: 18.9197,
    isCountyCity: true,
    urbanAreaId: 'gop',
  },
  {
    id: 'wodzislaw_slaski',
    name: 'Wodzisław Śląski',
    voivodeship: 'śląskie',
    powiat: 'wodzisławski',
    lat: 50.0031,
    lng: 18.4639,
  },
  {
    id: 'raciborz',
    name: 'Racibórz',
    voivodeship: 'śląskie',
    powiat: 'raciborski',
    lat: 50.0919,
    lng: 18.2192,
  },
  {
    id: 'zawiercie',
    name: 'Zawiercie',
    voivodeship: 'śląskie',
    powiat: 'zawierciański',
    lat: 50.4878,
    lng: 19.4167,
  },
  {
    id: 'cieszyn',
    name: 'Cieszyn',
    voivodeship: 'śląskie',
    powiat: 'cieszyński',
    lat: 49.7486,
    lng: 18.6331,
  },
  {
    id: 'zywiec',
    name: 'Żywiec',
    voivodeship: 'śląskie',
    powiat: 'żywiecki',
    lat: 49.6886,
    lng: 19.1939,
  },

  // --- Trójmiasto i Pomorze ---
  {
    id: 'sopot',
    name: 'Sopot',
    voivodeship: 'pomorskie',
    powiat: 'm. Sopot',
    lat: 54.4418,
    lng: 18.5601,
    isCountyCity: true,
    urbanAreaId: 'trojmiasto',
    aliases: ['3city', 'trojmiasto'],
  },
  {
    id: 'slupsk',
    name: 'Słupsk',
    voivodeship: 'pomorskie',
    powiat: 'm. Słupsk',
    lat: 54.4641,
    lng: 17.0287,
    isCountyCity: true,
  },
  {
    id: 'tczew',
    name: 'Tczew',
    voivodeship: 'pomorskie',
    powiat: 'tczewski',
    lat: 54.0925,
    lng: 18.7978,
  },
  {
    id: 'wejherowo',
    name: 'Wejherowo',
    voivodeship: 'pomorskie',
    powiat: 'wejherowski',
    lat: 54.6044,
    lng: 18.2344,
    urbanAreaId: 'trojmiasto',
  },
  {
    id: 'rumia',
    name: 'Rumia',
    voivodeship: 'pomorskie',
    powiat: 'wejherowski',
    lat: 54.5714,
    lng: 18.3975,
    urbanAreaId: 'trojmiasto',
  },
  {
    id: 'starogard_gdanski',
    name: 'Starogard Gdański',
    voivodeship: 'pomorskie',
    powiat: 'starogardzki',
    lat: 53.9639,
    lng: 18.5286,
  },
  {
    id: 'malbork',
    name: 'Malbork',
    voivodeship: 'pomorskie',
    powiat: 'malborski',
    lat: 54.0359,
    lng: 19.0266,
  },
  {
    id: 'kwidzyn',
    name: 'Kwidzyn',
    voivodeship: 'pomorskie',
    powiat: 'kwidzyński',
    lat: 53.7347,
    lng: 18.9317,
  },
  {
    id: 'chojnice',
    name: 'Chojnice',
    voivodeship: 'pomorskie',
    powiat: 'chojnicki',
    lat: 53.6958,
    lng: 17.5564,
  },

  // --- Mazowsze & Ziemia Łódzka ---
  {
    id: 'plock',
    name: 'Płock',
    voivodeship: 'mazowieckie',
    powiat: 'm. Płock',
    lat: 52.5463,
    lng: 19.7065,
    isCountyCity: true,
  },
  {
    id: 'siedlce',
    name: 'Siedlce',
    voivodeship: 'mazowieckie',
    powiat: 'm. Siedlce',
    lat: 52.1678,
    lng: 22.2858,
    isCountyCity: true,
  },
  {
    id: 'ostroleka',
    name: 'Ostrołęka',
    voivodeship: 'mazowieckie',
    powiat: 'm. Ostrołęka',
    lat: 53.0847,
    lng: 21.5739,
    isCountyCity: true,
  },
  {
    id: 'pruszkow',
    name: 'Pruszków',
    voivodeship: 'mazowieckie',
    powiat: 'pruszkowski',
    lat: 52.1706,
    lng: 20.8122,
    urbanAreaId: 'warszawa_metro',
  },
  {
    id: 'legionowo',
    name: 'Legionowo',
    voivodeship: 'mazowieckie',
    powiat: 'legionowski',
    lat: 52.4011,
    lng: 20.9328,
    urbanAreaId: 'warszawa_metro',
  },
  {
    id: 'piaseczno',
    name: 'Piaseczno',
    voivodeship: 'mazowieckie',
    powiat: 'piaseczyński',
    lat: 52.0747,
    lng: 21.0264,
    urbanAreaId: 'warszawa_metro',
  },
  {
    id: 'otwock',
    name: 'Otwock',
    voivodeship: 'mazowieckie',
    powiat: 'otwocki',
    lat: 52.1064,
    lng: 21.2628,
    urbanAreaId: 'warszawa_metro',
  },
  {
    id: 'ciechanow',
    name: 'Ciechanów',
    voivodeship: 'mazowieckie',
    powiat: 'ciechanowski',
    lat: 52.8789,
    lng: 20.6133,
  },
  {
    id: 'minsk_mazowiecki',
    name: 'Mińsk Mazowiecki',
    voivodeship: 'mazowieckie',
    powiat: 'miński',
    lat: 52.1794,
    lng: 21.5717,
  },
  {
    id: 'zyrardow',
    name: 'Żyrardów',
    voivodeship: 'mazowieckie',
    powiat: 'żyrardowski',
    lat: 52.0572,
    lng: 20.4439,
  },
  {
    id: 'sochaczew',
    name: 'Sochaczew',
    voivodeship: 'mazowieckie',
    powiat: 'sochaczewski',
    lat: 52.2289,
    lng: 20.2372,
  },
  {
    id: 'piotrkow_trybunalski',
    name: 'Piotrków Trybunalski',
    voivodeship: 'łódzkie',
    powiat: 'm. Piotrków Trybunalski',
    lat: 51.4053,
    lng: 19.7033,
    isCountyCity: true,
  },
  {
    id: 'skierniewice',
    name: 'Skierniewice',
    voivodeship: 'łódzkie',
    powiat: 'm. Skierniewice',
    lat: 51.9567,
    lng: 20.1444,
    isCountyCity: true,
  },
  {
    id: 'pabianice',
    name: 'Pabianice',
    voivodeship: 'łódzkie',
    powiat: 'pabianicki',
    lat: 51.6644,
    lng: 19.3556,
    urbanAreaId: 'lodz_metro',
  },
  {
    id: 'zgierz',
    name: 'Zgierz',
    voivodeship: 'łódzkie',
    powiat: 'zgierski',
    lat: 51.8569,
    lng: 19.4058,
    urbanAreaId: 'lodz_metro',
  },
  {
    id: 'tomaszow_mazowiecki',
    name: 'Tomaszów Mazowiecki',
    voivodeship: 'łódzkie',
    powiat: 'tomaszowski',
    lat: 51.5311,
    lng: 20.0083,
  },
  {
    id: 'belchatow',
    name: 'Bełchatów',
    voivodeship: 'łódzkie',
    powiat: 'bełchatowski',
    lat: 51.3686,
    lng: 19.3697,
  },
  {
    id: 'sieradz',
    name: 'Sieradz',
    voivodeship: 'łódzkie',
    powiat: 'sieradzki',
    lat: 51.5964,
    lng: 18.7303,
  },
  {
    id: 'kutno',
    name: 'Kutno',
    voivodeship: 'łódzkie',
    powiat: 'kutnowski',
    lat: 52.2325,
    lng: 19.3622,
  },

  // --- Dolny Śląsk & Opolszczyzna ---
  {
    id: 'walbrzych',
    name: 'Wałbrzych',
    voivodeship: 'dolnośląskie',
    powiat: 'm. Wałbrzych',
    lat: 50.7719,
    lng: 16.2847,
    isCountyCity: true,
  },
  {
    id: 'legnica',
    name: 'Legnica',
    voivodeship: 'dolnośląskie',
    powiat: 'm. Legnica',
    lat: 51.21,
    lng: 16.1619,
    isCountyCity: true,
  },
  {
    id: 'jelenia_gora',
    name: 'Jelenia Góra',
    voivodeship: 'dolnośląskie',
    powiat: 'm. Jelenia Góra',
    lat: 50.9044,
    lng: 15.7383,
    isCountyCity: true,
  },
  {
    id: 'lubin',
    name: 'Lubin',
    voivodeship: 'dolnośląskie',
    powiat: 'lubiński',
    lat: 51.4019,
    lng: 16.2014,
  },
  {
    id: 'glogow',
    name: 'Głogów',
    voivodeship: 'dolnośląskie',
    powiat: 'głogowski',
    lat: 51.6636,
    lng: 16.0844,
  },
  {
    id: 'swidnica',
    name: 'Świdnica',
    voivodeship: 'dolnośląskie',
    powiat: 'świdnicki',
    lat: 50.8436,
    lng: 16.4881,
  },
  {
    id: 'boleslawiec',
    name: 'Bolesławiec',
    voivodeship: 'dolnośląskie',
    powiat: 'bolesławiecki',
    lat: 51.2639,
    lng: 15.5653,
  },
  {
    id: 'olesnica',
    name: 'Oleśnica',
    voivodeship: 'dolnośląskie',
    powiat: 'oleśnicki',
    lat: 51.2089,
    lng: 17.3797,
  },
  {
    id: 'kedzierzyn_kozle',
    name: 'Kędzierzyn-Koźle',
    voivodeship: 'opolskie',
    powiat: 'kędzierzyńsko-kozielski',
    lat: 50.3456,
    lng: 18.2147,
  },
  {
    id: 'nysa',
    name: 'Nysa',
    voivodeship: 'opolskie',
    powiat: 'nyski',
    lat: 50.4739,
    lng: 17.3344,
  },
  {
    id: 'brzeg',
    name: 'Brzeg',
    voivodeship: 'opolskie',
    powiat: 'brzeski',
    lat: 50.8608,
    lng: 17.4697,
  },

  // --- Wielkopolska & Kujawy ---
  {
    id: 'kalisz',
    name: 'Kalisz',
    voivodeship: 'wielkopolskie',
    powiat: 'm. Kalisz',
    lat: 51.7611,
    lng: 18.0911,
    isCountyCity: true,
  },
  {
    id: 'konin',
    name: 'Konin',
    voivodeship: 'wielkopolskie',
    powiat: 'm. Konin',
    lat: 52.2233,
    lng: 18.2511,
    isCountyCity: true,
  },
  {
    id: 'leszno',
    name: 'Leszno',
    voivodeship: 'wielkopolskie',
    powiat: 'm. Leszno',
    lat: 51.8419,
    lng: 16.575,
    isCountyCity: true,
  },
  {
    id: 'pila',
    name: 'Piła',
    voivodeship: 'wielkopolskie',
    powiat: 'pilski',
    lat: 53.1517,
    lng: 16.7381,
  },
  {
    id: 'ostrow_wielkopolski',
    name: 'Ostrów Wielkopolski',
    voivodeship: 'wielkopolskie',
    powiat: 'ostrowski',
    lat: 51.655,
    lng: 17.8067,
  },
  {
    id: 'gniezno',
    name: 'Gniezno',
    voivodeship: 'wielkopolskie',
    powiat: 'gnieźnieński',
    lat: 52.5347,
    lng: 17.5828,
  },
  {
    id: 'wloclawek',
    name: 'Włocławek',
    voivodeship: 'kujawsko-pomorskie',
    powiat: 'm. Włocławek',
    lat: 52.6483,
    lng: 19.0678,
    isCountyCity: true,
  },
  {
    id: 'grudziadz',
    name: 'Grudziądz',
    voivodeship: 'kujawsko-pomorskie',
    powiat: 'm. Grudziądz',
    lat: 53.4842,
    lng: 18.7536,
    isCountyCity: true,
  },
  {
    id: 'inowroclaw',
    name: 'Inowrocław',
    voivodeship: 'kujawsko-pomorskie',
    powiat: 'inowrocławski',
    lat: 52.7958,
    lng: 18.2614,
  },

  // --- Zachodniopomorskie, Lubuskie & Warmia-Mazury ---
  {
    id: 'koszalin',
    name: 'Koszalin',
    voivodeship: 'zachodniopomorskie',
    powiat: 'm. Koszalin',
    lat: 54.1944,
    lng: 16.1722,
    isCountyCity: true,
  },
  {
    id: 'stargard',
    name: 'Stargard',
    voivodeship: 'zachodniopomorskie',
    powiat: 'stargardzki',
    lat: 53.3386,
    lng: 15.0447,
  },
  {
    id: 'kolobrzeg',
    name: 'Kołobrzeg',
    voivodeship: 'zachodniopomorskie',
    powiat: 'kołobrzeski',
    lat: 54.1761,
    lng: 15.5831,
  },
  {
    id: 'swinoujscie',
    name: 'Świnoujście',
    voivodeship: 'zachodniopomorskie',
    powiat: 'm. Świnoujście',
    lat: 53.91,
    lng: 14.2472,
    isCountyCity: true,
  },
  {
    id: 'szczecinek',
    name: 'Szczecinek',
    voivodeship: 'zachodniopomorskie',
    powiat: 'szczecinecki',
    lat: 53.7078,
    lng: 16.6989,
  },
  {
    id: 'nowa_sol',
    name: 'Nowa Sól',
    voivodeship: 'lubuskie',
    powiat: 'nowosolski',
    lat: 51.8028,
    lng: 15.7144,
  },
  {
    id: 'zary',
    name: 'Żary',
    voivodeship: 'lubuskie',
    powiat: 'żarski',
    lat: 51.6422,
    lng: 15.1378,
  },
  {
    id: 'elblag',
    name: 'Elbląg',
    voivodeship: 'warmińsko-mazurskie',
    powiat: 'm. Elbląg',
    lat: 54.1522,
    lng: 19.4089,
    isCountyCity: true,
  },
  {
    id: 'elk',
    name: 'Ełk',
    voivodeship: 'warmińsko-mazurskie',
    powiat: 'ełcki',
    lat: 53.8286,
    lng: 22.3606,
  },
  {
    id: 'ostroda',
    name: 'Ostróda',
    voivodeship: 'warmińsko-mazurskie',
    powiat: 'ostródzki',
    lat: 53.7039,
    lng: 19.9653,
  },
  {
    id: 'ilawa',
    name: 'Iława',
    voivodeship: 'warmińsko-mazurskie',
    powiat: 'iławski',
    lat: 53.5961,
    lng: 19.5656,
  },
  {
    id: 'gizycko',
    name: 'Giżycko',
    voivodeship: 'warmińsko-mazurskie',
    powiat: 'giżycki',
    lat: 54.0381,
    lng: 21.7644,
  },

  // --- Lubelszczyzna & Podlasie & Świętokrzyskie ---
  {
    id: 'zamosc',
    name: 'Zamość',
    voivodeship: 'lubelskie',
    powiat: 'm. Zamość',
    lat: 50.7231,
    lng: 23.2519,
    isCountyCity: true,
  },
  {
    id: 'chelm',
    name: 'Chełm',
    voivodeship: 'lubelskie',
    powiat: 'm. Chełm',
    lat: 51.1306,
    lng: 23.475,
    isCountyCity: true,
  },
  {
    id: 'biala_podlaska',
    name: 'Biała Podlaska',
    voivodeship: 'lubelskie',
    powiat: 'm. Biała Podlaska',
    lat: 52.0328,
    lng: 23.1167,
    isCountyCity: true,
  },
  {
    id: 'pulawy',
    name: 'Puławy',
    voivodeship: 'lubelskie',
    powiat: 'puławski',
    lat: 51.4164,
    lng: 21.9694,
  },
  {
    id: 'swidnik',
    name: 'Świdnik',
    voivodeship: 'lubelskie',
    powiat: 'świdnicki',
    lat: 51.2189,
    lng: 22.6961,
    urbanAreaId: 'lublin_metro',
  },
  {
    id: 'suwalki',
    name: 'Suwałki',
    voivodeship: 'podlaskie',
    powiat: 'm. Suwałki',
    lat: 54.1117,
    lng: 22.9308,
    isCountyCity: true,
  },
  {
    id: 'lomza',
    name: 'Łomża',
    voivodeship: 'podlaskie',
    powiat: 'm. Łomża',
    lat: 53.1781,
    lng: 22.0589,
    isCountyCity: true,
  },
  {
    id: 'augustow',
    name: 'Augustów',
    voivodeship: 'podlaskie',
    powiat: 'augustowski',
    lat: 53.8431,
    lng: 22.9794,
  },
  {
    id: 'ostrowiec_swietokrzyski',
    name: 'Ostrowiec Świętokrzyski',
    voivodeship: 'świętokrzyskie',
    powiat: 'ostrowiecki',
    lat: 50.9297,
    lng: 21.3853,
  },
  {
    id: 'starachowice',
    name: 'Starachowice',
    voivodeship: 'świętokrzyskie',
    powiat: 'starachowicki',
    lat: 51.0531,
    lng: 21.0706,
  },
  {
    id: 'skarzysko_kamienna',
    name: 'Skarżysko-Kamienna',
    voivodeship: 'świętokrzyskie',
    powiat: 'skarżyski',
    lat: 51.1147,
    lng: 20.8703,
  },
  {
    id: 'sandomierz',
    name: 'Sandomierz',
    voivodeship: 'świętokrzyskie',
    powiat: 'sandomierski',
    lat: 50.6828,
    lng: 21.7489,
  },
];
